Repository stolostron/multicluster-observability-operator, pull requests merged in 2021-06, with the labels that each got.

#559 fix infinite reconcile
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/observatorium.go
  pkg/deploying/deployer.go
Labels: approved, dco-signoff: yes, lgtm

#568 add recording rule for kube_pod_container_resource_requests
  manifests/base/config/metrics_allowlist.yaml
  manifests/base/grafana/dash-acm-clusters-overview.yaml
Labels: approved, dco-signoff: yes, lgtm

#569 added acm_policyreport_info
  manifests/base/config/metrics_allowlist.yaml
Labels: approved, dco-signoff: yes, lgtm

#570 fix problem in service update
  pkg/deploying/deployer.go
Labels: approved, dco-signoff: yes, lgtm

#567 update cookie secret for alertmanager proxy.
  manifests/base/alertmanager/alertmanager-proxy.yaml
  manifests/base/alertmanager/alertmanager-statefulset.yaml
  manifests/base/alertmanager/kustomization.yaml
  pkg/rendering/renderer_alertmanager.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm

#572 update thanos image
  pkg/config/config.go
Labels: dco-signoff: yes, lgtm

#578 remove default limits for endpoint-metrics-operator and metrics collector
  manifests/endpoint-observability/operator.yaml
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, lgtm

#579 update hub-info for new format.
  controllers/placementrule/hub_info_secret.go
  controllers/placementrule/hub_info_secret_test.go
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm

#575 Rhowingt/crit alert policy
  manifests/base/alertmanager/alert_rules.yaml
Labels: approved, dco-signoff: yes, lgtm

#582 add etcd panel, update default refresh, add 10m refresh
  manifests/base/grafana/dash-acm-clusters-overview.yaml
Labels: dco-signoff: yes, lgtm

#584 Adding description about PVs used
  docs/MoreAboutPersistentStorage.md
Labels: approved, dco-signoff: yes, lgtm

#585 renew the server certificate if existing one has different hosts
  pkg/certificates/certificates.go
Labels: approved, dco-signoff: yes, lgtm

#573 Status goroutings
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/multiclusterobservability_status.go
  controllers/multiclusterobservability/multiclusterobservability_status_test.go
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm

#586 revert PR #553 related change
  README.md
  manifests/base/proxy/deployment.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controller/multiclusterobservability/certificates.go
  pkg/controller/multiclusterobservability/multiclusterobservability_controller_test.go
  pkg/controller/multiclusterobservability/multiclusterobservability_status.go
  pkg/controller/multiclusterobservability/observatorium.go
  pkg/controller/multiclusterobservability/observatorium_test.go
  pkg/rendering/renderer.go
Labels: approved, dco-signoff: yes, lgtm

#591 Redo of PR
  docs/MoreAboutPersistentStorage.md
Labels: dco-signoff: yes, lgtm

#593 added policy report alert to a separate group
  manifests/base/alertmanager/alert_rules.yaml
Labels: dco-signoff: no, lgtm

#595 update clustermanagementaddon if it's updated during upgrade
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  config/rbac/mco_role.yaml
  pkg/util/clustermanagementaddon.go
Labels: approved, dco-signoff: yes, lgtm

#596 remove CRD ApiextensionsV1beta1 Client
  pkg/util/client.go
Labels: approved, dco-signoff: yes, lgtm

#598 Add minio example manifests
  example/minio/minio-deployment.yaml
  example/minio/minio-pvc.yaml
  example/minio/minio-secret.yaml
  example/minio/minio-service.yaml
Labels: approved, dco-signoff: yes, lgtm

#599 remove separate rbac resources from bundle manifests.
  Makefile.prow
  bundle/manifests/multicluster-observability-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/multicluster-observability-operator-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/multicluster-observability-operator_v1_serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm

#597 fix os detection in makefile.
  Makefile.prow
Labels: approved, dco-signoff: yes, lgtm

#592 update ingress to use networking.k8s.io/v1
  manifests/base/proxy/ingress.yaml
Labels: approved, dco-signoff: yes, lgtm

#576 add grafana dashboard example yaml
  tools/README.md
  tools/example/custom-dashboard.yaml
  tools/example/observability-metrics-custom-allowlist.yaml
Labels: approved, dco-signoff: yes, lgtm

#608 delete ownerReferences
  tools/setup-grafana-dev.sh
Labels: approved, dco-signoff: yes, lgtm

#612 delete ownerReferences
  tools/setup-grafana-dev.sh
Labels: approved, dco-signoff: yes, lgtm

#609 Use DeepEqual to replace DeepDerivative
  controllers/multiclusterobservability/multiclusterobservability_status.go
  controllers/multiclusterobservability/multiclusterobservability_status_test.go
Labels: approved, dco-signoff: yes, lgtm

#601 Disable development mode
  main.go
Labels: approved, dco-signoff: yes, lgtm

#611 fix resources watch across multiple namespaces.
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/placementrule/placementrule_controller.go
  go.mod
  go.sum
  main.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, lgtm

#607 expose rbac-query-proxy external api from mgmt-ingress to route
  controllers/multiclusterobservability/grafana.go
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  manifests/base/proxy/ca-bundle.yaml
  manifests/base/proxy/cluster-role.yaml
  manifests/base/proxy/cookie-secret.yaml
  manifests/base/proxy/deployment.yaml
  manifests/base/proxy/kustomization.yaml
  manifests/base/proxy/service.yaml
  pkg/config/config.go
  pkg/rendering/renderer.go
  pkg/rendering/renderer_proxy.go
  pkg/rendering/templates/templates.go
Labels: approved, dco-signoff: yes, lgtm

#614 Remove MCO CR dependecny
  tools/setup-grafana-dev.sh
Labels: approved, dco-signoff: yes, lgtm

#615 removed acm from policyreport metric name
  manifests/base/alertmanager/alert_rules.yaml
  manifests/base/config/metrics_allowlist.yaml
Labels: approved, dco-signoff: yes, lgtm

#600 start placement & cert controller only when mco CR available
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/placementrule/placementrule_controller.go
  main.go
  pkg/certificates/cert_controller.go
Labels: approved, dco-signoff: yes, lgtm

#605 Get operand name from environment if any
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/multiclusterobservability_status.go
  controllers/multiclusterobservability/observatorium.go
  controllers/multiclusterobservability/observatorium_test.go
  controllers/multiclusterobservability/placementrule.go
  controllers/multiclusterobservability/placementrule_test.go
  controllers/placementrule/placementrule_controller.go
  controllers/placementrule/placementrule_controller_test.go
  pkg/certificates/cert_controller.go
  pkg/certificates/cert_controller_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/rendering/renderer.go
  pkg/rendering/renderer_alertmanager.go
  pkg/rendering/renderer_grafana.go
  pkg/rendering/renderer_proxy.go
Labels: approved, dco-signoff: yes, lgtm

#613 update dependies.
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm

#617 Update overview chart
  docs/images/observability_overview_in_ocm.png
Labels: approved, dco-signoff: yes, lgtm

#619 remove hardcoded rbac proxy image
  pkg/rendering/renderer_proxy.go
Labels: approved, dco-signoff: yes, lgtm

#620 move proxy from open-cluster-management/rbac-query-proxy for testing
  proxy/Dockerfile
  proxy/Makefile
  proxy/OWNERS
  proxy/README.md
  proxy/cmd/main.go
  proxy/deploy/cluster-role-binding.yaml
  proxy/deploy/cluster-role.yaml
  proxy/deploy/deployment.yaml
  proxy/deploy/kustomization.yaml
  proxy/deploy/service-account.yaml
  proxy/deploy/service.yaml
  proxy/examples/managedcluster/cluster1.yaml
  proxy/examples/managedcluster/cluster2.yaml
  proxy/examples/rbac/README.md
  proxy/examples/rbac/admin-rbac.yaml
  proxy/examples/rbac/user1-rbac.yaml
  proxy/examples/rbac/user2-rbac.yaml
  proxy/go.mod
  proxy/go.sum
  proxy/pkg/proxy/proxy.go
  proxy/pkg/proxy/proxy_test.go
  proxy/pkg/proxy/tls.go
  proxy/pkg/rewrite/rewrite.go
  proxy/pkg/rewrite/rewrite_test.go
  proxy/pkg/util/user_project.go
  proxy/pkg/util/user_project_test.go
  proxy/pkg/util/util.go
  proxy/pkg/util/util_test.go
Labels: approved, dco-signoff: yes, lgtm

#621 update managedclusteraddon if it's updated during upgrade flow
  pkg/util/managedclusteraddon.go
Labels: approved, dco-signoff: yes, lgtm

#618 watch mch and read image manifest configmap by label.
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  bundle/manifests/observability.open-cluster-management.io_observabilityaddons.yaml
  config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml
  config/manager/manager.yaml
  config/rbac/mco_role.yaml
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/multiclusterobservability_status_test.go
  controllers/placementrule/placementrule_controller.go
  controllers/placementrule/placementrule_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, dco-signoff: yes, lgtm

#625 move mch out from the filteredcache
  main.go
Labels: approved, dco-signoff: yes, lgtm

#626 upgrade filtered cache to fix duplicated mch instances.
  go.mod
  go.sum
  main.go
Labels: approved, dco-signoff: yes, lgtm

#624 remove unused client and fix ut.
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/placementrule/placementrule_controller.go
  controllers/placementrule/placementrule_controller_test.go
  main.go
  pkg/util/client.go
Labels: approved, dco-signoff: yes, lgtm

#623 reuse existing name for upgrade flow
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  manifests/base/proxy/deployment.yaml
  pkg/certificates/cert_controller.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
  pkg/certificates/signer.go
  pkg/rendering/renderer_proxy.go
Labels: approved, dco-signoff: yes, lgtm

#627 add resource request for memcached-exporter
  controllers/multiclusterobservability/observatorium.go
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm

#628 wait for manifestwork crd before starting manager.
  main.go
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm

#631 Revert "wait for manifestwork crd before starting manager. (#628)"
  main.go
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm

#630 update mco operator display name in CSV.
  api/v1beta1/multiclusterobservability_types.go
  api/v1beta1/observabilityaddon_types.go
  api/v1beta2/multiclusterobservability_types.go
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  config/manifests/bases/multicluster-observability-operator.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm

#629 Update etcd dashboard
  manifests/base/grafana/dash-acm-clusters-overview.yaml
Labels: approved, dco-signoff: yes, lgtm
