Repository stolostron/multicluster-observability-operator, pull requests merged in 2021-03, with the labels that each got.

#379 Add prow files
  Dockerfile.prow
  Makefile.prow
Labels: approved

#380 update make prow
  Makefile.prow
Labels: approved, lgtm

#383 adding overview doc
  README.md
  docs/images/observability_overview_in_ocm.png
Labels: approved, lgtm

#384 Rename Go module
  .gitignore
  PROJECT
  config/default/kustomization.yaml
  controllers/multiclusterobservability/certificates.go
  controllers/multiclusterobservability/certificates_test.go
  controllers/multiclusterobservability/grafana.go
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/multiclusterobservability_status.go
  controllers/multiclusterobservability/multiclusterobservability_status_test.go
  controllers/multiclusterobservability/observatorium.go
  controllers/multiclusterobservability/observatorium_test.go
  controllers/multiclusterobservability/placementrule.go
  controllers/multiclusterobservability/placementrule_test.go
  controllers/placementrule/endpoint_metrics_operator.go
  controllers/placementrule/hub_info_secret.go
  controllers/placementrule/kubeconfig.go
  controllers/placementrule/manifestwork.go
  controllers/placementrule/manifestwork_test.go
  controllers/placementrule/obsaddon.go
  controllers/placementrule/obsaddon_test.go
  controllers/placementrule/placementrule_controller.go
  controllers/placementrule/placementrule_controller_test.go
  controllers/placementrule/status.go
  controllers/placementrule/status_test.go
  docs/setup-ceph-for-object-storage.md
  docs/setup-ocs-for-object-storage.md
  go.mod
  go.sum
  main.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/deploying/deployer.go
  pkg/rendering/patching/patcher.go
  pkg/rendering/patching/patcher_test.go
  pkg/rendering/renderer.go
  pkg/rendering/renderer_alertmanager.go
  pkg/rendering/renderer_grafana.go
  pkg/rendering/renderer_test.go
  pkg/rendering/templates/templates.go
  pkg/rendering/templates/templates_test.go
  pkg/util/obj_compare.go
  pkg/util/util.go
  pkg/util/util_test.go
  sonar-project.properties
Labels: approved, lgtm

#386 switch to use clusterrole to replace roles in each cluster namespace
  controllers/placementrule/placementrule_controller.go
  controllers/placementrule/serviceaccount.go
  controllers/placementrule/serviceaccount_test.go
Labels: approved, lgtm

#373 remove stale obsaddon
  cicd-scripts/run-e2e-tests.sh
  pkg/controller/placementrule/endpoint_config.go
  pkg/controller/placementrule/endpoint_config_test.go
  pkg/controller/placementrule/placementrule_controller.go
Labels: do-not-merge/hold, lgtm

#387 enable e2e to prow
  .travis.yml
  Makefile.prow
  RELEASE_FF_BRANCH
  RELEASE_MAIN_BRANCH
  cicd-scripts/run-e2e-tests.sh
  sonar-project.properties
Labels: approved, lgtm

#390 update golang.org/x/text to v0.3.5
  go.mod
  go.sum
Labels: approved, lgtm

#392 update golang.org/x/text to v0.3.5
  go.mod
  go.sum
Labels: approved, lgtm

#309 Support storage resize
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
Labels: approved, lgtm

#393 support custom component image.
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, lgtm

#394 add build and deploy the operator steps.
  README.md
Labels: approved, lgtm

#399 Update thanos to 0.18.0
  README.md
  bundle/manifests/core.observatorium.io_observatoria.yaml
  config/crd/bases/core.observatorium.io_observatoria.yaml
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/multiclusterobservability_status.go
  controllers/multiclusterobservability/observatorium.go
  controllers/multiclusterobservability/observatorium_test.go
  deploy/olm-catalog/multicluster-observability-operator/manifests/core.observatorium.io_observatoria.yaml
  deploy/req_crds/core.observatorium.io_observatoria.yaml
  go.mod
  go.sum
  manifests/base/proxy/deployment.yaml
  pkg/config/config.go
Labels: approved, lgtm

#403 fix go build complain for struct literal initialization.
  controllers/placementrule/obsaddon_test.go
Labels: approved, lgtm

#397 refactoring for obsaddon/manifestwork delete flow
  controllers/placementrule/manifestwork.go
  controllers/placementrule/obsaddon.go
  controllers/placementrule/placementrule_controller.go
  controllers/placementrule/status.go
Labels: approved, lgtm

#405 Fix readme typo
  README.md
Labels: approved, lgtm

#398 Upgrade grafana to 7.4.2
  pkg/config/config.go
Labels: approved, lgtm

#400 check placementrule CRD before apply placementrule.
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  main.go
  pkg/util/client.go
Labels: approved, lgtm

#401 update img to ocm upstream
  controllers/multiclusterobservability/observatorium.go
  pkg/config/config.go
Labels: approved, lgtm

#402 delete deprecated roles/manifestworks in 2.2
  controllers/placementrule/manifestwork.go
  controllers/placementrule/placementrule_controller.go
  controllers/placementrule/placementrule_controller_test.go
  controllers/placementrule/serviceaccount.go
  controllers/placementrule/serviceaccount_test.go
Labels: approved, lgtm

#406 update bundle
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  bundle/manifests/multicluster-observability-operator_v1_serviceaccount.yaml
  config/manager/kustomization.yaml
Labels: approved, lgtm

#408 handle null observabilityaddonspec
  controllers/placementrule/manifestwork.go
  controllers/placementrule/serviceaccount.go
  go.sum
Labels: approved, lgtm

#409 register placementrule reconciler when its CRD is installed.
  main.go
Labels: approved, lgtm

#414 Remove KubeAPIServerLatency alert, improve grafana dashboard performance
  manifests/base/alertmanager/alert_rules.yaml
  manifests/base/grafana/acm-multicluster-dash.yaml
Labels: approved, lgtm

#415 2.2 - Remove KubeAPIServerLatency alert, improve grafana dashboard performance
  manifests/base/alertmanager/alert_rules.yaml
Labels: lgtm

#417 test separation of acm-specific dashboards
  manifests/base/grafana/acm-clusters-overview-dash.yaml
  manifests/base/grafana/acm-optimization-overview-dash.yaml
  manifests/base/grafana/kustomization.yaml
Labels: approved, lgtm

#419 Handle resize the storage
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  pkg/util/util.go
Labels: approved, lgtm

#418 Simulate the metrics-collector
  tests/benchmark/clean-metrics-collector.sh
  tests/benchmark/metrics-collector-deployment-template.yaml
  tests/benchmark/metrics-collector-serving-certs-ca-bundle.yaml
  tests/benchmark/setup-metrics-collector.sh
Labels: approved, lgtm

#420 update samples.
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  config/samples/observability_v1beta1_multiclusterobservability.yaml
  config/samples/observability_v1beta2_multiclusterobservability.yaml
Labels: approved, lgtm

#422 Update placementrule go module dependency
  go.mod
  go.sum
Labels: approved, lgtm

#424 dissociate all dashboards
  manifests/base/grafana/dash-acm-clusters-overview.yaml
  manifests/base/grafana/dash-acm-optimization-overview.yaml
  manifests/base/grafana/dash-cluster-rsrc-use.yaml
  manifests/base/grafana/dash-k8s-apiserver.yaml
  manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
  manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
  manifests/base/grafana/dash-k8s-networking-cluster.yaml
  manifests/base/grafana/dash-node-rsrc-use.yaml
  manifests/base/grafana/k8s-mixin-dashboards.yaml
  manifests/base/grafana/kustomization.yaml
Labels: lgtm

#425 add permission for observatorium sa for crud of poddisruptionbudgets
  manifests/base/observatorium/cluster_role.yaml
Labels: approved, lgtm

#426 Upgrade obs to adopt new feature
  bundle/manifests/core.observatorium.io_observatoria.yaml
  config/crd/bases/core.observatorium.io_observatoria.yaml
  controllers/multiclusterobservability/observatorium.go
  controllers/multiclusterobservability/observatorium_test.go
  go.mod
  go.sum
Labels: approved, lgtm

#427 update webhook secret name.
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  bundle/manifests/multicluster-observability-webhook-service_v1_service.yaml
  config/certmanager/certificate.yaml
  config/default/manager_webhook_patch.yaml
  config/webhook/ocp_ssc_in_webhook_service.yaml
Labels: approved, lgtm

#428 update acm-clusters-overview dash
  manifests/base/grafana/acm-clusters-overview-dash.yaml
Labels: approved, lgtm

#429 remove deploy dir due to sdk upgrade
  bundle/manifests/core.observatorium.io_observatoria.yaml
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  deploy/crds/observability.open-cluster-management.io_multiclusterobservabilities_crd.yaml
  deploy/crds/observability.open-cluster-management.io_v1beta1_multiclusterobservability_cr.yaml
  deploy/olm-catalog/multicluster-observability-operator/manifests/core.observatorium.io_observatoria.yaml
  deploy/olm-catalog/multicluster-observability-operator/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  deploy/olm-catalog/multicluster-observability-operator/manifests/observability.open-cluster-management.io_multiclusterobservabilities_crd.yaml
  deploy/olm-catalog/multicluster-observability-operator/manifests/observability.open-cluster-management.io_observabilityaddon_crd.yaml
  deploy/operator.yaml
  deploy/req_crds/core.observatorium.io_observatoria.yaml
  deploy/req_crds/observability.open-cluster-management.io_observabilityaddon_crd.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, lgtm

#430 add deprecated message for v1beta1 version.
  Makefile.prow
  bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
Labels: approved, lgtm

#432 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, lgtm

#423 update api document
  docs/MultiClusterObservability-CRD.md
Labels: approved, lgtm
