Repository stolostron/multicluster-observability-operator, pull requests merged in 2021-08, with the labels that each got.

#673 fix code smell and vulnerabilities
  collectors/metrics/pkg/simulator/simulator.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/placementrule/obsaddon.go
  operators/multiclusterobservability/controllers/placementrule/role.go
  operators/multiclusterobservability/pkg/certificates/cert_controller.go
  operators/multiclusterobservability/pkg/certificates/certificates.go
  operators/multiclusterobservability/pkg/config/config.go
  operators/pkg/config/hub_info.go
  tests/pkg/utils/mco_dashboard.go
  tests/pkg/utils/mco_deploy.go
  tests/pkg/utils/mco_deployments.go
  tests/pkg/utils/mco_metric.go
Labels: approved, dco-signoff: yes, lgtm

#679 Gke
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/multiclusterobservability/controllers/placementrule/endpoint_metrics_operator.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/manifests/endpoint-observability/operator.yaml
  operators/multiclusterobservability/manifests/prometheus/kustomization.yaml
  operators/multiclusterobservability/manifests/prometheus/prometheus_service.yaml
  operators/multiclusterobservability/pkg/util/obj_compare.go
  operators/pkg/config/constants.go
Labels: approved, dco-signoff: yes, lgtm

#668 Add Assisted Installer metrics to metrics_allowlist
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Labels: approved, dco-signoff: yes, lgtm

#680 fix build and ut from root directory.
  Makefile
  operators/multiclusterobservability/Dockerfile
  operators/multiclusterobservability/Makefile
Labels: approved, dco-signoff: yes, lgtm

#682 Fix vulnerabilities
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/multiclusterobservability/pkg/config/config.go
  tests/pkg/utils/mco_dashboard.go
  tests/pkg/utils/mco_metric.go
Labels: approved, dco-signoff: yes, lgtm

#683 Should not clean image manifests after delete mco cr
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm

#681 enable validating webhook for MCO
  collectors/metrics/test/integration/manifests/client-serving-certs-ca-bundle.yaml
  operators/multiclusterobservability/PROJECT
  operators/multiclusterobservability/api/v1beta2/multiclusterobservability_webhook.go
  operators/multiclusterobservability/api/v1beta2/zz_generated.deepcopy.go
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/config/certmanager/certificate.yaml
  operators/multiclusterobservability/config/certmanager/kustomization.yaml
  operators/multiclusterobservability/config/certmanager/kustomizeconfig.yaml
  operators/multiclusterobservability/config/crd/kustomization.yaml
  operators/multiclusterobservability/config/crd/kustomizeconfig.yaml
  operators/multiclusterobservability/config/crd/patches/cainjection_in_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/patches/cainjection_in_observabilityaddons.yaml
  operators/multiclusterobservability/config/crd/patches/webhook_in_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/patches/webhook_in_observabilityaddons.yaml
  operators/multiclusterobservability/config/crd/patches/webhook_multiclusterobservabilities_cainjection_patch.yaml
  operators/multiclusterobservability/config/default/kustomization.yaml
  operators/multiclusterobservability/config/default/manager_auth_proxy_patch.yaml
  operators/multiclusterobservability/config/default/manager_config_patch.yaml
  operators/multiclusterobservability/config/manager/controller_manager_config.yaml
  operators/multiclusterobservability/config/manager/kustomization.yaml
  operators/multiclusterobservability/config/manager/manager_webhook_patch.yaml
  operators/multiclusterobservability/config/manifests/kustomization.yaml
  operators/multiclusterobservability/config/prometheus/kustomization.yaml
  operators/multiclusterobservability/config/prometheus/monitor.yaml
  operators/multiclusterobservability/config/rbac/auth_proxy_client_clusterrole.yaml
  operators/multiclusterobservability/config/rbac/auth_proxy_role.yaml
  operators/multiclusterobservability/config/rbac/auth_proxy_role_binding.yaml
  operators/multiclusterobservability/config/rbac/auth_proxy_service.yaml
  operators/multiclusterobservability/config/rbac/kustomization.yaml
  operators/multiclusterobservability/config/rbac/leader_election_role.yaml
  operators/multiclusterobservability/config/rbac/leader_election_role_binding.yaml
  operators/multiclusterobservability/config/rbac/multiclusterobservability_editor_role.yaml
  operators/multiclusterobservability/config/rbac/multiclusterobservability_viewer_role.yaml
  operators/multiclusterobservability/config/rbac/observabilityaddon_editor_role.yaml
  operators/multiclusterobservability/config/rbac/observabilityaddon_viewer_role.yaml
  operators/multiclusterobservability/config/rbac/role_binding.yaml
  operators/multiclusterobservability/config/scorecard/bases/config.yaml
  operators/multiclusterobservability/config/scorecard/kustomization.yaml
  operators/multiclusterobservability/config/scorecard/patches/basic.config.yaml
  operators/multiclusterobservability/config/scorecard/patches/olm.config.yaml
  operators/multiclusterobservability/config/webhook/kustomization.yaml
  operators/multiclusterobservability/config/webhook/manifests.yaml
  operators/multiclusterobservability/config/webhook/validatingwebhookconfiguration.yaml
  operators/multiclusterobservability/config/webhook/webhook_cainjection_patch.yaml
  operators/multiclusterobservability/config/webhook/webhook_service_cert_patch.yaml
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-cabundle.yaml
Labels: approved, dco-signoff: yes, lgtm

#684 Enable pprof
  operators/endpointmetrics/main.go
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/config/manager/manager.yaml
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/manifests/endpoint-observability/operator.yaml
  operators/pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm

#685 update components resource request
  examples/mco/e2e/v1beta2/observability.yaml
  operators/multiclusterobservability/manifests/base/observatorium/operator.yaml
  operators/multiclusterobservability/manifests/endpoint-observability/operator.yaml
  operators/multiclusterobservability/pkg/config/config.go
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/utils/mco_deploy.go
Labels: lgtm, approved, dco-signoff: yes

#690 format dockerfile
  collectors/metrics/Dockerfile
Labels: lgtm, approved, dco-signoff: yes

#688 make mco wait for mch ready before reconciling and reading image manifests
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
Labels: lgtm, approved, dco-signoff: yes

#692 fix the clustername key used in hubinfo secret
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#691 Register debug to http.DefaultServeMux
  operators/pkg/util/util.go
Labels: lgtm, approved, dco-signoff: yes

#693 correct managedcluster delete process
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/utils/mco_namespace.go
Labels: lgtm, approved, dco-signoff: yes

#677 enable some e2e test case
  docs/setup-ocs-for-object-storage.md
  tests/grafana-dev-test.sh
  tests/pkg/tests/observability_grafana_dev_test.go
Labels: lgtm, approved, dco-signoff: yes

#672 cherrypick 669 to cleanup cache for mco cr deletion
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved, dco-signoff: yes

#694 run e2e tests based on code changes
  cicd-scripts/customize-mco.sh
  cicd-scripts/run-e2e-tests.sh
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/tests/observability_certrenew_test.go
  tests/pkg/tests/observability_config_test.go
  tests/pkg/tests/observability_dashboard_test.go
  tests/pkg/tests/observability_default_config_test.go
  tests/pkg/tests/observability_grafana_dev_test.go
  tests/pkg/tests/observability_metrics_test.go
Labels: lgtm, approved, dco-signoff: yes

#661 update label refresh option
  manifests/base/grafana/dash-acm-clusters-overview.yaml
  manifests/base/grafana/dash-acm-optimization-overview.yaml
  manifests/base/grafana/dash-cluster-rsrc-use.yaml
  manifests/base/grafana/dash-k8s-apiserver.yaml
  manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
  manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
  manifests/base/grafana/dash-k8s-etcd.yaml
  manifests/base/grafana/dash-k8s-networking-cluster.yaml
  manifests/base/grafana/dash-node-rsrc-use.yaml
Labels: lgtm, approved, dco-signoff: yes

#697 change MinVersion to tls.VersionTLS13
  collectors/metrics/pkg/metricsclient/metricsclient.go
Labels: lgtm, approved, dco-signoff: yes

#700 merge missing commits from rbac-query-proxy repo
  proxy/cmd/main.go
  proxy/deploy/deployment.yaml
  proxy/pkg/proxy/tls.go
Labels: lgtm, approved, dco-signoff: yes

#687 update components resource request
  manifests/base/observatorium/operator.yaml
  manifests/endpoint-observability/operator.yaml
  pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#689 fix e2e setup script.
  cicd-scripts/run-e2e-tests.sh
  cicd-scripts/setup-e2e-tests.sh
Labels: lgtm, approved, dco-signoff: yes

#707 updated sonar-project.properties
  sonar-project.properties
Labels: lgtm, dco-signoff: yes

#706 updated sonar-project.properties
  sonar-project.properties
Labels: lgtm, dco-signoff: yes

#705 updated sonar-project.properties
  sonar-project.properties
Labels: lgtm, dco-signoff: yes

#699 update label refresh option
  manifests/base/grafana/acm-multicluster-dash.yaml
  manifests/base/grafana/k8s-mixin-dashboards.yaml
Labels: dco-signoff: yes

#703 add POD_NAMESPACE environment and check ResourceVersion
  loaders/dashboards/pkg/controller/dashboard_controller.go
  operators/multiclusterobservability/manifests/base/grafana/deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#704 cherrypick 688 to fix image manifest read issue.
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/observatorium_test.go
  controllers/placementrule/placementrule_controller.go
Labels: lgtm, approved, dco-signoff: yes

#702 add filter for rbac resources and managedclusteraddon in cache.
  go.mod
  go.sum
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/role.go
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/pkg/util/managedclusteraddon.go
  operators/multiclusterobservability/pkg/util/managedclusteraddon_test.go
Labels: lgtm, approved, dco-signoff: yes

#708 Pass POD_NAMESPACE in
  manifests/base/grafana/deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#709 optimize template load and render.
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  operators/multiclusterobservability/controllers/placementrule/endpoint_metrics_operator.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/pkg/rendering/renderer.go
  operators/multiclusterobservability/pkg/rendering/renderer_test.go
  operators/multiclusterobservability/pkg/rendering/templates/templates.go
  operators/multiclusterobservability/pkg/rendering/templates/templates_test.go
Labels: lgtm, approved, dco-signoff: yes

#711 add managedcluster simulator tool for mco.
  tools/simulator/managed-cluster/README.md
  tools/simulator/managed-cluster/setup-managedcluster.sh
  tools/simulator/metrics-collector/Dockerfile
  tools/simulator/metrics-collector/Makefile
  tools/simulator/metrics-collector/README.md
  tools/simulator/metrics-collector/clean-metrics-collector.sh
  tools/simulator/metrics-collector/metrics-collector-view.yaml
  tools/simulator/metrics-collector/setup-metrics-collector.sh
Labels: lgtm, approved, dco-signoff: yes

#710 fix update logic for managedclusteraddon.
  operators/multiclusterobservability/pkg/util/managedclusteraddon.go
Labels: lgtm, approved, dco-signoff: yes

#716 util pkg refactoring
  operators/endpointmetrics/pkg/rendering/renderer.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  operators/multiclusterobservability/controllers/placementrule/endpoint_metrics_operator.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/obsaddon.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/pkg/certificates/cert_controller.go
  operators/multiclusterobservability/pkg/certificates/certificates.go
  operators/multiclusterobservability/pkg/rendering/renderer.go
  operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
  operators/multiclusterobservability/pkg/rendering/renderer_grafana.go
  operators/multiclusterobservability/pkg/rendering/renderer_proxy.go
  operators/multiclusterobservability/pkg/util/client.go
  operators/multiclusterobservability/pkg/util/obj_compare.go
  operators/multiclusterobservability/pkg/util/util.go
  operators/multiclusterobservability/pkg/util/util_test.go
  operators/pkg/rendering/patching/patcher.go
  operators/pkg/util/obj_compare.go
  operators/pkg/util/obj_compare_test.go
  operators/pkg/util/util.go
Labels: lgtm, approved, dco-signoff: yes

#717 Enable observability addons
  tests/pkg/tests/observability_addon_test.go
Labels: lgtm, approved, dco-signoff: yes

#714 Revert "change MinVersion to tls.VersionTLS13"
  collectors/metrics/pkg/metricsclient/metricsclient.go
Labels: lgtm, approved, dco-signoff: yes

#718 support alert forward from *KS.
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go
  operators/endpointmetrics/manifests/prometheus/kubernetes-monitoring-alertingrules.yaml
  operators/endpointmetrics/manifests/prometheus/kustomization.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-config.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-statefulset.yaml
  operators/endpointmetrics/pkg/rendering/renderer.go
  operators/endpointmetrics/pkg/rendering/renderer_test.go
Labels: lgtm, approved, dco-signoff: yes

#719 add sonar scan exception
  collectors/metrics/pkg/forwarder/forwarder.go
Labels: lgtm, approved, dco-signoff: yes

#720 introduce config-reloader for prometheus to fix CA totation on *KS.
  operators/endpointmetrics/manifests/prometheus/prometheus-statefulset.yaml
  operators/endpointmetrics/pkg/rendering/renderer.go
  operators/multiclusterobservability/manifests/endpoint-observability/images.yaml
  operators/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#722 e2e for *ks support
  examples/metrics/allowlist/custom-metrics-allowlist.yaml
  tests/pkg/tests/observability_grafana_test.go
  tests/pkg/tests/observability_metrics_test.go
  tests/pkg/utils/mco_managedcluster.go
Labels: lgtm, approved, dco-signoff: yes

#732 reduce the duplicated loop for creating managedcluster resources
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#733 fix stopCheckReady receive signal hang for status update.
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_status.go
Labels: lgtm, approved, dco-signoff: yes
