Repository stolostron/multicluster-observability-operator, pull requests merged in 2021-09, with the labels that each got.

#735 update service discovery for metrics endpoints in kubelet
  operators/endpointmetrics/manifests/prometheus/prometheus-clusterRole.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-config.yaml
  operators/multiclusterobservability/manifests/endpoint-observability/role.yaml
Labels: lgtm, approved, dco-signoff: yes

#736 increase the resource limit for mco.
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/config/manager/manager.yaml
Labels: lgtm, approved, dco-signoff: yes

#715 replace route in kind testing env.
  examples/minio/minio-deployment.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  operators/multiclusterobservability/controllers/placementrule/hub_info_secret.go
  operators/multiclusterobservability/controllers/placementrule/hub_info_secret_test.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/manifests/base/grafana/deployment.yaml
  operators/multiclusterobservability/pkg/certificates/cert_controller.go
  operators/multiclusterobservability/pkg/certificates/cert_controller_test.go
  operators/multiclusterobservability/pkg/certificates/certificates.go
  operators/multiclusterobservability/pkg/certificates/certificates_test.go
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/rendering/renderer_grafana.go
Labels: lgtm, approved, dco-signoff: yes

#737 allow simulated metrics-collectors be scheduled to master node.
  tools/simulator/metrics-collector/README.md
  tools/simulator/metrics-collector/setup-metrics-collector.sh
Labels: lgtm, approved, dco-signoff: yes

#740 fix required fields for mco.
  operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
  operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
Labels: lgtm, approved, dco-signoff: yes

#742 support all nonocp platforms & observatorium metrics support
  go.mod
  go.sum
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/config/rbac/mco_role.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/manifests/base/observatorium/kustomization.yaml
  operators/multiclusterobservability/manifests/base/observatorium/prometheus_role.yaml
  operators/multiclusterobservability/manifests/base/observatorium/prometheus_role_binding.yaml
  operators/multiclusterobservability/pkg/servicemonitor/sm_controller.go
  operators/multiclusterobservability/pkg/servicemonitor/sm_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#743 use release 2.3 to run e2e
  cicd-scripts/setup-e2e-tests.sh
Labels: lgtm, approved, dco-signoff: yes

#734 Adding Grafana dashboard for SLO/SLI
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml
Labels: approved, dco-signoff: yes

#745 Update to use ResourceVersion instead of Generation for MCO CR Update
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
Labels: lgtm, approved, dco-signoff: yes

#744 remove resources from simulated metrics-collector.
  tests/benchmark/setup-metrics-collector.sh
Labels: lgtm, approved, dco-signoff: yes

#746 add REMEDIATE.md to trigger rebuild all images
  REMEDIATE.md
Labels: lgtm, approved, dco-signoff: yes

#747 Update golang to 1.17
  collectors/metrics/Dockerfile
  go.mod
  go.sum
  loaders/dashboards/Dockerfile
  operators/endpointmetrics/Dockerfile
  operators/multiclusterobservability/Dockerfile
  proxy/Dockerfile
  tests/Dockerfile
Labels: lgtm, approved, dco-signoff: yes

#748 updated api server latency panel labels
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-apiserver.yaml
Labels: lgtm, approved, dco-signoff: yes

#750 avoid unnecessary restart during deployment
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/pkg/certificates/cert_controller.go
  operators/multiclusterobservability/pkg/certificates/cert_controller_test.go
  operators/multiclusterobservability/pkg/servicemonitor/sm_controller.go
  operators/multiclusterobservability/pkg/servicemonitor/sm_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#752 update label_values() in dashboards to avoid heavy query
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-cluster-rsrc-use.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-apiserver.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-etcd.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-networking-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-node-rsrc-use.yaml
Labels: lgtm, approved, dco-signoff: yes

#756 2.2.8 => 2.2.9
  COMPONENT_VERSION
  deploy/olm-catalog/multicluster-observability-operator/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: dco-signoff: no

#751 Fix addon-framework issue
  go.mod
  go.sum
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go
  operators/endpointmetrics/controllers/status/status_controller_test.go
  operators/endpointmetrics/pkg/util/lease.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
  operators/multiclusterobservability/controllers/placementrule/status.go
  operators/multiclusterobservability/controllers/placementrule/status_test.go
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/pkg/certificates/approver.go
  operators/multiclusterobservability/pkg/certificates/approver_test.go
  operators/multiclusterobservability/pkg/certificates/cert_agent.go
  operators/multiclusterobservability/pkg/certificates/cert_agent_test.go
  operators/multiclusterobservability/pkg/certificates/cert_controller.go
  operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
  operators/multiclusterobservability/pkg/util/clustermanagementaddon_test.go
  operators/multiclusterobservability/pkg/util/managedclusteraddon.go
  operators/multiclusterobservability/pkg/util/managedclusteraddon_test.go
  proxy/cmd/main.go
  proxy/pkg/util/util.go
  tests/pkg/tests/observability_install_test.go
Labels: lgtm, approved, dco-signoff: yes

#757 Revert "Depend on MCH loosely"
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
Labels: lgtm, approved, dco-signoff: no

#759 Remove . to make it works in grafana8
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
Labels: lgtm, approved, dco-signoff: yes

#753 remove mco namespace check and add mch resource update for managedcluster resources
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#761 fetch original images from quay.io
  manifests/base/grafana/deployment.yaml
  pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#754 replace image for managedcluster resource for mch update event.
  controllers/placementrule/placementrule_controller.go
  controllers/placementrule/placementrule_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#758 Add description in optimization overview
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#760 in non-ocp, disable useless metrics scrape in prometheus
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/manifests/prometheus/prometheus-config.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-statefulset.yaml
  operators/endpointmetrics/pkg/rendering/renderer.go
  operators/endpointmetrics/pkg/rendering/renderer_test.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/pkg/config/config.go
  operators/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#686 add webhook controller and e2e testing for validating webhook
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/config/rbac/mco_role.yaml
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/util/client.go
  operators/multiclusterobservability/pkg/webhook/webhook_controller.go
  operators/multiclusterobservability/pkg/webhook/webhook_controller_test.go
  tests/pkg/utils/mco_deploy.go
  tests/pkg/utils/utils.go
Labels: lgtm, approved, dco-signoff: yes

#764 update memcached img
  operators/multiclusterobservability/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#767 fix sonar scan issues for webhook controller.
  operators/multiclusterobservability/pkg/webhook/webhook_controller.go
Labels: lgtm, approved, dco-signoff: yes

#766 Fix broken link in readme : )
  README.md
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#762 updated service-level overview dashboard label and descriptions
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server-cluster.yaml
Labels: lgtm, approved, dco-signoff: yes

#768 for API errors in dashboard, display 0 if result is empty
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#765 update memcached img
  pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#763 update default scrape interval to 5 minutes
  cicd-scripts/run-e2e-tests.sh
  examples/mco/e2e/v1beta1/observability-v1beta1-to-v1beta2-golden.yaml
  go.mod
  go.sum
  operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
  operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_observabilityaddons.yaml
  operators/multiclusterobservability/config/crd/bases/core.observatorium.io_observatoria.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-cluster-rsrc-use.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-apiserver.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-etcd.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-node-rsrc-use.yaml
  operators/multiclusterobservability/manifests/endpoint-observability/observability.open-cluster-management.io_observabilityaddon_crd.yaml
Labels: lgtm, approved, dco-signoff: yes

#749 added fleet level dashboard for SLO status
  operators/multiclusterobservability/manifests/base/alertmanager/alert_rules.yaml
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server.yaml
  operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml
Labels: approved, dco-signoff: yes

#770 add custom image registry feature for mangedcluster
  go.mod
  go.sum
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/config/rbac/mco_role.yaml
  operators/multiclusterobservability/controllers/placementrule/customize_img.go
  operators/multiclusterobservability/controllers/placementrule/endpoint_metrics_operator.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/main.go
Labels: lgtm, approved, dco-signoff: yes

#769 use topk for cpu/memory optimization/utilization panels.
  operators/multiclusterobservability/manifests/base/alertmanager/alert_rules.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#772 fix no data in dashboard for rate interval.
  operators/multiclusterobservability/manifests/base/alertmanager/alert_rules.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#773 fix no data in grafana cluster overview dashboard
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#771 Check OBA and managedclusteraddon are ready for all managed clusters before verify metrics etc
  cicd-scripts/setup-e2e-tests.sh
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/tests/observability_install_test.go
  tests/pkg/utils/mco_oba.go
Labels: lgtm, approved, dco-signoff: yes

#774 Combine to use one query per panel
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#776 add ut for custom registry
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#777 remove unused merge transform from cluster overview dashboard.
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#778 2.1.11 => 2.1.12
  COMPONENT_VERSION
  deploy/olm-catalog/multicluster-observability-operator/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: dco-signoff: no

#779 Updated SLO dashboard label and remove SLO name from recording rule
  operators/multiclusterobservability/manifests/base/alertmanager/alert_rules.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server-cluster.yaml
Labels: lgtm, approved, dco-signoff: yes

#781 fix row missing for iks in apiserver panel.
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#780 update minio image used2 in e2e
  tests/e2e/minio/minio-deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#782 Correct the deepEqual logic
  operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
Labels: lgtm, approved, dco-signoff: yes

#784 fix customized registry issue
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#785 return error when no managedcluster
  tests/pkg/utils/mco_managedcluster.go
Labels: lgtm, approved, dco-signoff: yes

#786 update label "cluster" to "Cluster" in dashboards for consistent naming
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-etcd.yaml
Labels: lgtm, approved, dco-signoff: yes
