Repository stolostron/multicluster-observability-operator, pull requests merged in 2021-04, with the labels that each got.

#431 Tackle replicas
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/observatorium.go
  controllers/multiclusterobservability/observatorium_test.go
  main.go
Labels: approved, lgtm

#436 Support configure replicas for alertmanager/grafana/rbac-query-proxy
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/multiclusterobservability_status.go
  controllers/multiclusterobservability/observatorium.go
  controllers/multiclusterobservability/observatorium_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/rendering/renderer.go
  pkg/rendering/renderer_alertmanager.go
  pkg/rendering/renderer_grafana.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, lgtm

#434 upgrade ingress version
  bundle/manifests/multicluster-observability-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  config/rbac/mco_role.yaml
  manifests/base/grafana/ingress.yaml
Labels: approved, lgtm

#437 support roks
  bundle/manifests/multicluster-observability-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/rbac/mco_role.yaml
  controllers/placementrule/kubeconfig.go
  controllers/placementrule/kubeconfig_test.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, lgtm

#438 create namespace if it doesn't exist.
  controllers/multiclusterobservability/multiclusterobservability_controller.go
Labels: approved, lgtm

#440 Update CR Ready status condition
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/multiclusterobservability_status.go
Labels: approved, lgtm

#442 update status in mca
  controllers/placementrule/placementrule_controller.go
  controllers/placementrule/status.go
  pkg/util/managedclusteraddon.go
Labels: approved, lgtm

#444 adopts new https endpoint for rbac proxy
  controllers/multiclusterobservability/grafana.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  manifests/base/proxy/ca-bundle.yaml
  manifests/base/proxy/deployment.yaml
  manifests/base/proxy/ingress.yaml
  manifests/base/proxy/kustomization.yaml
  manifests/base/proxy/service.yaml
Labels: approved, lgtm

#441 manage the storageversionmigration resource for api migration.
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  config/rbac/mco_role.yaml
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/storageversionmigration.go
  controllers/multiclusterobservability/storageversionmigration_test.go
  controllers/placementrule/serviceaccount.go
  controllers/placementrule/serviceaccount_test.go
  go.mod
  go.sum
  main.go
  pkg/config/config.go
Labels: approved, lgtm

#446 Update crds version
  bundle/manifests/core.observatorium.io_observatoria.yaml
  config/crd/bases/core.observatorium.io_observatoria.yaml
Labels: approved, lgtm

#449 update base image to multiarch and fix doc.
  Dockerfile.prow
  README.md
Labels: approved, lgtm

#433 Dash updates
  manifests/base/grafana/acm-clusters-overview-dash.yaml
  manifests/base/grafana/acm-optimization-overview-dash.yaml
  manifests/base/grafana/dash-k8s-apiserver.yaml
  manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
  manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  manifests/base/grafana/dash-k8s-networking-cluster.yaml
Labels: approved, lgtm

#452 Revert "fix base image not found issue."
  Dockerfile.prow
Labels: approved, lgtm

#445 set up manager and watch resource with new operator-sdk style.
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/placementrule/placementrule_controller.go
Labels: approved, lgtm

#435 update alertmgr img to ocm upstream
  manifests/base/alertmanager/alertmanager-statefulset.yaml
  pkg/config/config.go
  pkg/rendering/renderer_alertmanager.go
Labels: approved, lgtm

#453 remove min interval from memory usage, add networking dash
  manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  manifests/base/grafana/dash-k8s-networking-namespace-pods.yaml
  manifests/base/grafana/dash-k8s-networking-pod.yaml
  manifests/base/grafana/kustomization.yaml
Labels: approved, lgtm

#448 update grafana deploy name
  tools/generate-dashboard-configmap-yaml.sh
  tools/setup-grafana-dev.sh
  tools/switch-to-grafana-admin.sh
Labels: approved, lgtm

#447 update observatorium image
  controllers/multiclusterobservability/observatorium.go
  pkg/config/config.go
Labels: approved, lgtm

#456 Update scripts to replace --export
  tests/benchmark/setup-metrics-collector.sh
Labels: approved, lgtm

#460 update dashes, fix workload dash metric bug
  manifests/base/grafana/acm-clusters-overview-dash.yaml
  manifests/base/grafana/acm-optimization-overview-dash.yaml
  manifests/base/grafana/dash-acm-clusters-overview.yaml
  manifests/base/grafana/dash-acm-optimization-overview.yaml
  manifests/base/grafana/dash-k8s-apiserver.yaml
  manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
  manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
  manifests/base/grafana/dash-k8s-networking-cluster.yaml
  manifests/base/grafana/dash-k8s-networking-namespace-pods.yaml
  manifests/base/grafana/dash-k8s-networking-pod.yaml
Labels: approved, dco-signoff: yes, lgtm

#457 update fsGroup value from pod
  manifests/base/grafana/deployment.yaml
  tools/setup-grafana-dev.sh
Labels: approved, lgtm

#458 cert refactoring, remove cert-mgr dependency
  CONTRIBUTING.md
  bundle/manifests/multicluster-observability-operator-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/rbac/mco_role.yaml
  controllers/multiclusterobservability/certificates.go
  controllers/multiclusterobservability/certificates_test.go
  controllers/multiclusterobservability/multiclusterobservability_controller.go
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/observatorium.go
  controllers/placementrule/kubeconfig.go
  controllers/placementrule/kubeconfig_test.go
  controllers/placementrule/manifestwork.go
  controllers/placementrule/manifestwork_test.go
  controllers/placementrule/obsaddon_test.go
  controllers/placementrule/placementrule_controller.go
  controllers/placementrule/placementrule_controller_test.go
  controllers/placementrule/role.go
  controllers/placementrule/role_test.go
  go.mod
  go.sum
  main.go
  manifests/endpoint-observability/operator.yaml
  pkg/certificates/approver.go
  pkg/certificates/cert_agent.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
  pkg/certificates/signer.go
  pkg/config/config.go
  pkg/util/managedclusteraddon.go
  pkg/util/managedclusteraddon_test.go
Labels: approved, dco-signoff: yes, lgtm

#464 remove client cert generation for managed cluster
  controllers/placementrule/manifestwork.go
  controllers/placementrule/placementrule_controller.go
  pkg/certificates/certificates.go
Labels: approved, dco-signoff: yes, lgtm

#465 remove certmanager dependency.
  README.md
Labels: approved, dco-signoff: yes, lgtm

#439 supports roks in acm 2.2
  deploy/olm-catalog/multicluster-observability-operator/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controller/placementrule/kubeconfig.go
  pkg/controller/placementrule/kubeconfig_test.go
Labels: approved, lgtm

#469 delete dashboard uid avoid conflict wit old dashboard
  tools/generate-dashboard-configmap-yaml.sh
Labels: approved, dco-signoff: yes, lgtm

#466 delete dashboard uid avoid conflict with old dashboard
  tools/generate-dashboard-configmap-yaml.sh
  tools/setup-grafana-dev.sh
Labels: approved, dco-signoff: yes, lgtm

#470 use only one manifestwork in observability
  controllers/placementrule/manifestwork.go
  controllers/placementrule/manifestwork_test.go
  controllers/placementrule/placementrule_controller.go
  controllers/placementrule/placementrule_controller_test.go
Labels: approved, dco-signoff: yes, lgtm

#471 add microdnf update
  Dockerfile.prow
Labels: approved, dco-signoff: yes, lgtm

#474 Grant permission to serviceaccount
  deploy/olm-catalog/multicluster-observability-operator/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  deploy/role.yaml
Labels: dco-signoff: yes, lgtm

#472 add prow build badge.
  README.md
Labels: approved, dco-signoff: yes, lgtm

#455 Enable serviceMonitor
  bundle/manifests/core.observatorium.io_observatoria.yaml
  config/crd/bases/core.observatorium.io_observatoria.yaml
  controllers/multiclusterobservability/observatorium.go
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm

#473 Support configure retentionConfig in MCO CR
  api/v1beta2/multiclusterobservability_types.go
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  controllers/multiclusterobservability/observatorium.go
Labels: approved, dco-signoff: yes, lgtm

#462 Add resource limits
  api/v1beta2/multiclusterobservability_types.go
  api/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  config/samples/observability_v1beta2_multiclusterobservability.yaml
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/observatorium.go
  controllers/multiclusterobservability/observatorium_test.go
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm

#476 add new metrics for 4.8, update renames
  manifests/base/config/metrics_allowlist.yaml
Labels: approved, dco-signoff: yes

#480 add renamed metric
  manifests/base/config/metrics_allowlist.yaml
Labels: approved, dco-signoff: yes, lgtm

#477 Revert "Add resource limits"
  api/v1beta2/multiclusterobservability_types.go
  api/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  config/samples/observability_v1beta2_multiclusterobservability.yaml
  controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  controllers/multiclusterobservability/observatorium.go
  controllers/multiclusterobservability/observatorium_test.go
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm

#479 set log level to info
  manifests/base/observatorium/operator.yaml
Labels: approved, dco-signoff: yes, lgtm

#485 update observatorium crd
  bundle/manifests/core.observatorium.io_observatoria.yaml
  config/crd/bases/core.observatorium.io_observatoria.yaml
Labels: approved, dco-signoff: yes, lgtm

#482 fix image replace issue
  controllers/multiclusterobservability/observatorium.go
  pkg/config/config.go
  pkg/rendering/renderer_alertmanager.go
Labels: approved, dco-signoff: yes, lgtm

#486 add kube_node_status_capacity metric
  manifests/base/config/metrics_allowlist.yaml
Labels: approved, dco-signoff: yes, lgtm

#490 fix dns issue for alertmanager cluster peers.
  manifests/base/alertmanager/alertmanager-statefulset.yaml
  pkg/rendering/renderer_alertmanager.go
Labels: approved, dco-signoff: yes, lgtm

#489 upgrade golang to 1.16
  Dockerfile.prow
  go.mod
Labels: approved, dco-signoff: yes, lgtm

#487 remove addon's finalizer forcely after delete it 5 minutes later
  controllers/placementrule/obsaddon.go
  controllers/placementrule/obsaddon_test.go
  controllers/placementrule/placementrule_controller.go
Labels: approved, dco-signoff: yes, lgtm

#481 cert rotation
  main.go
  pkg/certificates/cert_controller.go
  pkg/certificates/certificates.go
Labels: approved, dco-signoff: yes, lgtm

#492 Have the registration and registration-operator image fixed
  tests/e2e/setup.sh
Labels: approved, dco-signoff: yes, lgtm

#488 update queries with compatable metrics across supported ocp clusters for acm2.3
  manifests/base/grafana/dash-acm-clusters-overview.yaml
  manifests/base/grafana/dash-acm-optimization-overview.yaml
  manifests/base/grafana/dash-cluster-rsrc-use.yaml
  manifests/base/grafana/dash-k8s-apiserver.yaml
  manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
  manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
  manifests/base/grafana/dash-k8s-networking-cluster.yaml
  manifests/base/grafana/dash-k8s-networking-namespace-pods.yaml
  manifests/base/grafana/dash-k8s-networking-pod.yaml
  manifests/base/grafana/dash-node-rsrc-use.yaml
Labels: approved, dco-signoff: yes, lgtm

#491 fix incorrect name.
  api/v1beta2/multiclusterobservability_conversion.go
  api/v1beta2/multiclusterobservability_webhook.go
  config/crd/kustomization.yaml
  config/crd/patches/ocp_ssc_webhook_multiclusterobservabilities.yaml
Labels: approved, dco-signoff: yes, lgtm

#497 Support configuring queryFrontendCache
  bundle/manifests/core.observatorium.io_observatoria.yaml
  config/crd/bases/core.observatorium.io_observatoria.yaml
  controllers/multiclusterobservability/observatorium.go
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm

#478 Update replicationFactor to 3
  controllers/multiclusterobservability/observatorium.go
Labels: approved, dco-signoff: yes, lgtm

#494 Update simulator to create cert
  tests/benchmark/setup-metrics-collector.sh
Labels: approved, dco-signoff: yes, lgtm

#495 update thanos-receive-controller img due to upgrade golang to 1.16
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm

#496 remove CleanupInterval
  docs/MultiClusterObservability-CRD.md
Labels: approved, dco-signoff: yes, lgtm

#498 update owners
  OWNERS
Labels: approved, dco-signoff: yes, lgtm
