Repository stolostron/multicluster-observability-operator, pull requests merged in 2022-03, with the labels that each got.

#919 fix mismatch capital in testing label.
  tests/format-results.sh
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/tests/observability_alert_test.go
  tests/pkg/tests/observability_certrenew_test.go
  tests/pkg/tests/observability_config_test.go
  tests/pkg/tests/observability_dashboard_test.go
  tests/pkg/tests/observability_endpoint_preserve_test.go
  tests/pkg/tests/observability_grafana_dev_test.go
  tests/pkg/tests/observability_grafana_test.go
  tests/pkg/tests/observability_manifestwork_test.go
  tests/pkg/tests/observability_metrics_test.go
  tests/pkg/tests/observability_observatorium_preserve_test.go
  tests/pkg/tests/observability_reconcile_test.go
  tests/pkg/tests/observability_retention_test.go
  tests/pkg/tests/observability_route_test.go
Labels: lgtm, approved, dco-signoff: yes

#921 Enabled Github Dependabot
  .github/dependabot.yml
Labels: lgtm, approved, dco-signoff: yes

#922 Removed unneeded vendor for dependabot file
  .github/dependabot.yml
Labels: lgtm, dco-signoff: yes

#929 2.3.6 => 2.3.7
  COMPONENT_VERSION
Labels: lgtm, approved, dco-signoff: no

#916 Added collect rules to metrics allowlist
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Labels: lgtm, approved, dco-signoff: yes

#908 Add Backup labels to observability resources
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  operators/multiclusterobservability/pkg/certificates/certificates.go
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/util/backuputil.go
Labels: lgtm, approved, dco-signoff: yes

#933 adding experimental alert dashboards
  examples/dashboards/alert-dashboards/README.md
  examples/dashboards/alert-dashboards/alert-analysis.yaml
  examples/dashboards/alert-dashboards/alerts-by-cluster.yaml
  examples/dashboards/alert-dashboards/clusters-by-alert.yaml
  examples/dashboards/alert-dashboards/kustomization.yaml
Labels: lgtm, approved, dco-signoff: yes

#931 support WriteStorage
  go.mod
  go.sum
  operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
  operators/multiclusterobservability/api/v1beta2/zz_generated.deepcopy.go
  operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
  operators/multiclusterobservability/pkg/util/remotewriteendpoint.go
  operators/multiclusterobservability/pkg/util/remotewriteendpoint_test.go
Labels: lgtm, approved, dco-signoff: yes

#935 add observabilityaddon spec nil check.
  pkg/controller/placementrule/placementrule_controller.go
Labels: lgtm, approved, dco-signoff: yes

#936 Support configuring sa annotations for query/rule/compact/receive/store
  examples/mco/e2e/v1beta2/custom-certs/observability.yaml
  examples/mco/e2e/v1beta2/observability.yaml
  go.mod
  go.sum
  operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
  operators/multiclusterobservability/api/v1beta2/zz_generated.deepcopy.go
  operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/core.observatorium.io_observatoria.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  tests/pkg/tests/observability_config_test.go
  tests/pkg/utils/mco_sa.go
Labels: lgtm, approved, dco-signoff: yes

#939 add the PrometheusRule for remote write alert
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/config/rbac/mco_role.yaml
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/manifests/base/alertmanager/kustomization.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/prometheusrule.yaml
  tests/run-in-kind/req_crds/prometheusrule-crd.yaml
Labels: lgtm, approved, dco-signoff: yes

#940 Rename rules to recording_rules, update collect_rules schema
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Labels: lgtm, approved, dco-signoff: yes

#938 Added recording rules to metrics allowlist & refactored Grafana dashboards
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
Labels: lgtm, approved, dco-signoff: yes

#946 support dynamic collect in metrics-collector
  collectors/metrics/cmd/metrics-collector/main.go
  collectors/metrics/pkg/collectrule/evaluator.go
  collectors/metrics/pkg/collectrule/evaluator_test.go
  collectors/metrics/pkg/forwarder/forwarder.go
Labels: lgtm, approved, dco-signoff: yes

#947 Added observatorium-dynamic datasource to dashboards
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
Labels: lgtm, approved, dco-signoff: yes

#948 support dynamic metrics collection in endpoint operator
  collectors/metrics/pkg/metricsclient/metricsclient.go
  examples/gen.go
  operators/endpointmetrics/controllers/observabilityendpoint/match_evaluator.go
  operators/endpointmetrics/controllers/observabilityendpoint/match_evaluator_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/pkg/config/types.go
Labels: lgtm, approved, dco-signoff: yes

#917 upgrade go dependency for security fix.
  go.mod
  go.sum
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
Labels: lgtm, approved, dco-signoff: yes

#951 add the rule name as a label for hash
  collectors/metrics/pkg/collectrule/evaluator.go
  collectors/metrics/pkg/collectrule/evaluator_test.go
Labels: lgtm, approved, dco-signoff: yes

#950 Set dynamic datasource interval to default when collect rules are empty
  operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#952 Added missing recording rules
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
Labels: lgtm, approved, dco-signoff: yes

#953 update the collect rules based on resourcequota
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Labels: lgtm, approved, dco-signoff: yes

#955 update promql to get cluster memory usage
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Labels: lgtm, approved, dco-signoff: yes

#957 noop to trigger build
  REMEDIATE.md
Labels: dco-signoff: yes

#958 disable metrics collection which defined in collect rule
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
Labels: lgtm, approved, dco-signoff: yes

#959 Support SNO collect rules only
  operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#960 Reverted to original datasource Grafana
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
Labels: lgtm, dco-signoff: yes

#961 Add additional approvers
  OWNERS
Labels: lgtm, approved, dco-signoff: yes

#964 update collect rules schema
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/pkg/config/types.go
Labels: lgtm, approved, dco-signoff: yes

#962 fix metrics collector simulator.
  tools/simulator/metrics-collector/generate-metrics-data.sh
Labels: lgtm, approved, dco-signoff: yes

#967 set dynamic interval
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
Labels: lgtm, approved, dco-signoff: yes

#968 add missing backup labels
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/pkg/certificates/certificates.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#969 Remove access_key and secret_key validation
  operators/multiclusterobservability/pkg/config/obj_storage_conf_test.go
  operators/multiclusterobservability/pkg/config/s3_conf.go
Labels: lgtm, approved, dco-signoff: yes

#971 update collect rule to use matches
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Labels: lgtm, approved, dco-signoff: yes

#972 handle crd comparison of different api versions: v1 and v1beta1
  operators/pkg/util/obj_compare.go
  operators/pkg/util/obj_compare_test.go
Labels: lgtm, approved, dco-signoff: yes

#973 use absolute url for grafana link
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
Labels: lgtm, approved, dco-signoff: yes

#975 hide nodetype selector for "summary by node" dashboard.
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-summary-by-node-ocp311.yaml
Labels: lgtm, approved, dco-signoff: yes

#977 2.3.8 => 2.3.9
  COMPONENT_VERSION
Labels: dco-signoff: no

#978 update collect rule, fix collect bug
  collectors/metrics/pkg/collectrule/evaluator.go
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Labels: lgtm, approved, dco-signoff: yes

#979 add permission for finalizers of addons
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/config/rbac/mco_role.yaml
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
Labels: lgtm, approved, dco-signoff: yes

#980 trigger build of all images for openssl fix
  REMEDIATE.md
Labels: lgtm, approved, dco-signoff: yes
