Repository stolostron/multicluster-observability-operator, pull requests merged in 2022-02, with the labels that each got.

#885 empty to trigger build
  README.md
Labels: dco-signoff: yes

#882 Added github action for updating go modules
  .github/workflow/go-package-update.yml
Labels: lgtm, dco-signoff: yes

#883 also check metrics-collector pod status when disable obs
  tests/pkg/tests/observability_addon_test.go
Labels: lgtm, approved, dco-signoff: yes

#884 also check metrics-collector pod status when disable obs(2.4)
  tests/pkg/tests/observability_addon_test.go
Labels: lgtm, approved, dco-signoff: yes

#888 fix broken links for ocp311 dashboards.
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-namespaces-in-cluster-ocp311.yaml
Labels: lgtm, approved, dco-signoff: yes

#889 updated github workflow
  .github/workflows/go-package-update.yml
Labels: lgtm, dco-signoff: yes

#892 fix: updated github workflow
  .github/workflows/go-package-update.yml
Labels: lgtm, dco-signoff: yes

#886 2.4 - delete obs addon when enableMetrics is set to false
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/utils/mco_oba.go
Labels: lgtm, approved, dco-signoff: yes

#893 delete obs addon when enableMetrics is set to false
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/utils/mco_oba.go
Labels: lgtm, approved, dco-signoff: yes

#880 use prometheus operator in *KS to launch prometheus
  examples/alerts/watchdog_rule/kustomization.yaml
  examples/alerts/watchdog_rule/watchdog-rule.yaml
  operators/endpointmetrics/main.go
  operators/endpointmetrics/manifests/prometheus/crd/alertmanager_crd_0_53_1.yaml
  operators/endpointmetrics/manifests/prometheus/crd/alertmanagerconfig_crd_0_53_1.yaml
  operators/endpointmetrics/manifests/prometheus/crd/kustomization.yaml
  operators/endpointmetrics/manifests/prometheus/crd/podmonitor_crd_0_53_1.yaml
  operators/endpointmetrics/manifests/prometheus/crd/probe_crd_0_53_1.yaml
  operators/endpointmetrics/manifests/prometheus/crd/prometheus_crd_0_53_1.yaml
  operators/endpointmetrics/manifests/prometheus/crd/prometheusrule_crd_0_53_1.yaml
  operators/endpointmetrics/manifests/prometheus/crd/servicemonitor_crd_0_53_1.yaml
  operators/endpointmetrics/manifests/prometheus/crd/thanosruler_crd_0_53_1.yaml
  operators/endpointmetrics/manifests/prometheus/kube-prometheus-rules.yaml
  operators/endpointmetrics/manifests/prometheus/kubernetes-monitoring-alertingrules.yaml
  operators/endpointmetrics/manifests/prometheus/kubernetes-monitoring-rules.yaml
  operators/endpointmetrics/manifests/prometheus/kustomization.yaml
  operators/endpointmetrics/manifests/prometheus/node-exporter-rules.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-alertmanager-config-secret.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-operator-deployment.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-operator-role.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-operator-roleBinding.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-operator-serviceAccount.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-resource.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-scrape-targets-secret.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-statefulset.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/k8s.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/kube-apiserver-availability.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/kube-apiserver-histogram.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/kube-apiserver.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/kube-prometheus-general.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/kube-prometheus-node-recording.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/kube-scheduler.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/kubelet.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/kubernetes-monitoring-alertingrules.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/kustomization.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/node-exporter.yaml
  operators/endpointmetrics/manifests/prometheus/prometheusrules/node.yaml
  operators/endpointmetrics/pkg/rendering/renderer.go
  operators/endpointmetrics/pkg/rendering/templates/templates.go
  operators/multiclusterobservability/controllers/placementrule/endpoint_metrics_operator.go
  operators/multiclusterobservability/manifests/endpoint-observability/images.yaml
  operators/multiclusterobservability/manifests/endpoint-observability/role.yaml
  operators/pkg/config/config.go
  operators/pkg/deploying/deployer.go
  operators/pkg/rendering/renderer.go
  operators/pkg/util/obj_compare.go
  tests/pkg/tests/observability_alert_test.go
  tests/pkg/utils/utils.go
Labels: lgtm, approved, dco-signoff: yes

#894 empty pr to trigger build
  REMEDIATE.md
Labels: lgtm, approved, dco-signoff: yes

#895 empty pr to trigger build
  operators/endpointmetrics/README.md
Labels: dco-signoff: yes

#896 added continue on error to debug gh actions
  .github/workflows/go-package-update.yml
Labels: lgtm, approved, dco-signoff: yes

#898 delete managed components when enableMetrics=false bugzilla 203197
  controllers/placementrule/placementrule_controller.go
Labels: lgtm, approved, dco-signoff: yes

#897 fix broken link in grafana dashboards.
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-namespaces-in-cluster-ocp311.yaml
Labels: lgtm, approved, dco-signoff: yes

#900 rbac proxy can handle query from POST request
  proxy/pkg/util/util.go
Labels: lgtm, approved, dco-signoff: yes

#903 fix error reported by sonar
  proxy/pkg/util/util.go
Labels: lgtm, approved, dco-signoff: yes

#904 handle query rewrite in POST request
  proxy/pkg/util/util.go
Labels: lgtm, approved, dco-signoff: yes

#905 Delete managed components when enableMetrics=false bugzilla 203197
  pkg/controller/placementrule/placementrule_controller.go
Labels: lgtm, approved, dco-signoff: yes

#902 Updated Github action
  .github/workflows/go-package-dependencies-update.yml
  .github/workflows/go-package-update.yml
Labels: lgtm, approved, dco-signoff: yes

#907 Fixed sed action within gh action automation
  .github/workflows/go-package-dependencies-update.yml
Labels: lgtm, approved, dco-signoff: yes

#910 Fix unsupported chars for configmap name
  tools/generate-dashboard-configmap-yaml.sh
Labels: lgtm, approved, dco-signoff: yes

#914 check the compact pod is restarted and ready
  tests/pkg/tests/observability_observatorium_preserve_test.go
Labels: lgtm, approved, dco-signoff: yes
