Repository stolostron/multicluster-observability-operator, pull requests merged in 2022-06, with the labels that each got.

#1027 update peer value in alertmanager sts to handle upgrade case(2.4)
  operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
Labels: lgtm, approved, dco-signoff: yes

#1021 [release-2.3] Triggering image rebuild
  README.md
Labels: lgtm, approved, dco-signoff: yes

#1035 [release-2.4] Added project component version
  COMPONENT_VERSION
Labels: lgtm, dco-signoff: yes

#1034 [release-2.5] Added project component version
  COMPONENT_VERSION
Labels: lgtm, approved, dco-signoff: yes

#1041 update the peer value in alertmanager sts to handle upgrade case(2.5)
  operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
Labels: lgtm, approved, dco-signoff: yes

#1033 [release-2.6] Added project component version
  COMPONENT_VERSION
Labels: lgtm, approved, dco-signoff: yes

#1045 [release-2.6] Triggering image rebuild
  README.md
Labels: lgtm, approved, dco-signoff: yes

#1046 2.3.11 => 2.3.12
  COMPONENT_VERSION
Labels: dco-signoff: yes
