Repository stolostron/multicluster-observability-operator, pull requests merged in 2023-04, with the labels that each got.

#1174 Readme For Finer Grained RBAC feature
  dev-previews/fine-grain-rbac/README.md
Labels: dco-signoff: yes

#1176 support serviceaccountprojection in mco/observatorium cr
  go.mod
  go.sum
  operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
  operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/core.observatorium.io_observatoria.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
Labels: lgtm, approved, dco-signoff: yes

#1177 [ACM-4956] use cluster_version metric for cluster labels
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-cluster-rsrc-use.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-networking-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-node-rsrc-use.yaml
Labels: lgtm, approved, dco-signoff: yes

#1181 use metrics consistently for cpu and memory overestimation
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
Labels: lgtm, approved

#1178 [ACM-5057] Use cluster_version metric for cluster label_values (#1177)
  cicd-scripts/run-e2e-tests.sh
  examples/minio-tls/minio-pvc.yaml
  examples/minio/minio-pvc.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-cluster-rsrc-use.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-networking-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-node-rsrc-use.yaml
Labels: lgtm, approved, dco-signoff: yes

#1182 [ACM-5061] Updated "USE Method / Node" dashboard to allow multiple node selection
  operators/multiclusterobservability/manifests/base/grafana/dash-node-rsrc-use.yaml
Labels: lgtm, approved, dco-signoff: yes

#1184 [ACM-5059] - Update dashboards to use relative time range when drilling down
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-optimization-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-cluster-rsrc-use.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-apiserver.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-namespace-workloads.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-node-pods.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-pod.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-compute-resources-workload.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-etcd.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-networking-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server-cluster.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-k8s-service-level-overview-api-server.yaml
Labels: lgtm, approved, dco-signoff: yes
