Repository stolostron/multicluster-observability-operator, pull requests merged in 2024-06, with the labels that each got.

#1469 [release-2.10] Backport optimized grafana dash
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview-optimized.yaml
  operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml
  tests/pkg/tests/observability_dashboard_test.go
Labels: lgtm, approved, dco-signoff: yes

#1464 [ACM-10269] Stamp CSR's organization units with the hash of the CA bundle
  go.mod
  operators/multiclusterobservability/pkg/certificates/cert_agent.go
  operators/multiclusterobservability/pkg/certificates/cert_agent_test.go
  operators/multiclusterobservability/pkg/certificates/cert_controller.go
  operators/multiclusterobservability/pkg/certificates/test_helpers.go
Labels: lgtm, approved, dco-signoff: yes

#1468 [ACM-10544] Upgrade addon-manager and k8s libs through custom controller-filtered-cache
  collectors/metrics/cmd/metrics-collector/main.go
  collectors/metrics/pkg/metricsclient/metricsclient.go
  collectors/metrics/pkg/simulator/simulator.go
  collectors/metrics/pkg/status/status.go
  go.mod
  go.sum
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_integration_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go
  operators/endpointmetrics/controllers/status/status_controller_integration_test.go
  operators/endpointmetrics/controllers/status/status_controller_test.go
  operators/endpointmetrics/main.go
  operators/endpointmetrics/pkg/rendering/renderer.go
  operators/endpointmetrics/pkg/rendering/renderer_test.go
  operators/endpointmetrics/pkg/util/status_test.go
  operators/multiclusterobservability/api/v1beta2/multiclusterobservability_webhook.go
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_observabilityaddons.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_status_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  operators/multiclusterobservability/controllers/placementrule/hub_info_secret_test.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/controllers/placementrule/obsaddon.go
  operators/multiclusterobservability/controllers/placementrule/obsaddon_test.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
  operators/multiclusterobservability/controllers/placementrule/status_test.go
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-accessor-clusterrole.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-accessor-clusterrolebinding.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-clusterrole.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-clusterrolebinding.yaml
  operators/multiclusterobservability/manifests/base/grafana/cluster-role-binding.yaml
  operators/multiclusterobservability/manifests/base/grafana/cluster-role.yaml
  operators/multiclusterobservability/manifests/base/observatorium/cluster_role.yaml
  operators/multiclusterobservability/manifests/base/observatorium/cluster_role_binding.yaml
  operators/multiclusterobservability/manifests/base/observatorium/prometheus_role_binding.yaml
  operators/multiclusterobservability/manifests/base/proxy/cluster-role-binding.yaml
  operators/multiclusterobservability/manifests/base/proxy/cluster-role.yaml
  operators/multiclusterobservability/manifests/base/thanos/thanos-ruler-clusterrole.yaml
  operators/multiclusterobservability/manifests/base/thanos/thanos-ruler-clusterrolebinding.yaml
  operators/multiclusterobservability/manifests/endpoint-observability/aggregate_role.yaml
  operators/multiclusterobservability/manifests/endpoint-observability/role.yaml
  operators/multiclusterobservability/manifests/endpoint-observability/role_binding.yaml
  operators/multiclusterobservability/pkg/rendering/renderer_test.go
  operators/multiclusterobservability/pkg/util/managedclusteraddon.go
  operators/multiclusterobservability/pkg/util/managedclusteraddon_test.go
Labels: lgtm, approved, dco-signoff: yes

#1471 Remove unused query to get obs api route-host
  operators/multiclusterobservability/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#1473 Prevent unnecessary update of observatorium in MCO
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
Labels: lgtm, approved, dco-signoff: yes

#1474 ACM-11991: add user number in kube-state-metrics
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/pkg/microshift/microshift.go
  operators/endpointmetrics/pkg/rendering/renderer.go
  operators/endpointmetrics/pkg/rendering/renderer_test.go
Labels: lgtm, approved, dco-signoff: yes

#1479 Add Observatorium API's external host to tls certs SAN
  operators/multiclusterobservability/pkg/certificates/certificates.go
Labels: lgtm, approved, dco-signoff: yes

#1477 Fix manifestwork update due to incorrect obj compare
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#1475 docker: Update sha for ubi image in dev dockerfile
  operators/multiclusterobservability/Dockerfile.dev
Labels: lgtm, approved, dco-signoff: yes

#1478 Automate go tool binary installations across scripts and Makefiles
  .bingo/Variables.mk
  .bingo/controller-gen.mod
  .bingo/controller-gen.sum
  .bingo/gojsontoyaml.mod
  .bingo/gojsontoyaml.sum
  .bingo/kind.mod
  .bingo/kind.sum
  .bingo/kustomize.mod
  .bingo/kustomize.sum
  .bingo/operator-sdk.mod
  .bingo/operator-sdk.sum
  .bingo/variables.env
  DEVELOPMENT.md
  Makefile
  cicd-scripts/run-e2e-in-kind-via-prow.sh
  cicd-scripts/update-check-mco-csv.sh
  collectors/metrics/README.md
  operators/multiclusterobservability/Makefile
  scripts/bootstrap-kind-env.sh
  scripts/install-binaries.sh
  tools/simulator/metrics-collector/generate-metrics-data.sh
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1482 Add OpenShift Log Storage team members
  OWNERS
Labels: lgtm, approved, dco-signoff: yes, needs-ok-to-test, do-not-merge/invalid-owners-file

#1484 Fix code setting global var with the MCO CR name
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func.go
Labels: lgtm, approved, dco-signoff: yes

#1486 Make URL handling safer and less wasteful
  operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
  operators/multiclusterobservability/controllers/placementrule/hub_info_secret.go
  operators/multiclusterobservability/pkg/certificates/certificates.go
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/config/config_test.go
Labels: lgtm, approved, dco-signoff: yes

#1485 ACM-11985: fix addon status update
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/pkg/util/status.go
  operators/endpointmetrics/pkg/util/status_test.go
Labels: lgtm, approved, dco-signoff: yes

#1483 Ensure MCO reconciles for actual updates
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/pkg/util/obj_compare.go
Labels: approved, dco-signoff: yes

#1487 ACM-11985: remove duplicated conditions
  operators/endpointmetrics/pkg/util/status.go
  operators/endpointmetrics/pkg/util/status_test.go
Labels: lgtm, approved, dco-signoff: yes

#1490 Clean owners files
  collectors/metrics/OWNERS
  loaders/dashboards/OWNERS
  operators/endpointmetrics/OWNERS
  operators/multiclusterobservability/OWNERS
  proxy/OWNERS
  tests/OWNERS
Labels: lgtm, approved, dco-signoff: yes

#1295 [ACM-8879]: Add initial implementation for T-shirt sizing ACM o11y resources
  operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/config/config_test.go
  operators/multiclusterobservability/pkg/config/resources.go
  operators/multiclusterobservability/pkg/config/resources_map.go
  operators/multiclusterobservability/pkg/config/resources_test.go
  operators/multiclusterobservability/pkg/rendering/renderer.go
  operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
  operators/multiclusterobservability/pkg/rendering/renderer_grafana.go
  operators/multiclusterobservability/pkg/rendering/renderer_proxy.go
  operators/multiclusterobservability/pkg/rendering/renderer_thanos.go
Labels: lgtm, approved, dco-signoff: yes

#1476 Wait for vendor label on managedcluster object
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
Labels: lgtm, approved, dco-signoff: yes

#1401 [ACM-10865] fine-grain-rbac tech-preview
  go.mod
  go.sum
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  proxy/cmd/main.go
  proxy/pkg/config/config.go
  proxy/pkg/proxy/proxy.go
  proxy/pkg/util/util.go
  proxy/pkg/util/util_test.go
  tech-previews/fine-grain-rbac/README.md
Labels: duplicate, approved, dco-signoff: yes, dependencies

#1497 Wait for OpenshiftVersion label when managed cluster is added
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
Labels: lgtm, approved, dco-signoff: yes

#1500 ACM-11987: Add self-managed to ClusterManagementAddOn
  operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
  operators/multiclusterobservability/pkg/util/clustermanagementaddon_test.go
Labels: lgtm, approved, dco-signoff: yes

#1496 Backport MCO reconcile issues to 2.10
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
  operators/pkg/util/obj_compare.go
Labels: lgtm, approved, dco-signoff: yes

#1498 fix: CVE-2023-45288 upgrade golang/x/net to 0.26
  .github/workflows/go-package-dependencies-update.yml
  collectors/metrics/Containerfile.operator
  collectors/metrics/Dockerfile
  go.mod
  go.sum
  loaders/dashboards/Containerfile.operator
  loaders/dashboards/Dockerfile
  operators/endpointmetrics/Containerfile.operator
  operators/endpointmetrics/Dockerfile
  operators/multiclusterobservability/Containerfile.operator
  operators/multiclusterobservability/Dockerfile
  operators/multiclusterobservability/Dockerfile.dev
  proxy/Containerfile.operator
  proxy/Dockerfile
  tests/Containerfile.operator
  tests/Dockerfile
  tools/simulator/alert-forward/Containerfile.operator
  tools/simulator/alert-forward/Dockerfile
  tools/simulator/metrics-collector/Dockerfile
  tools/simulator/metrics-collector/metrics-extractor/Containerfile.operator
  tools/simulator/metrics-collector/metrics-extractor/Dockerfile
Labels: lgtm, approved, dco-signoff: yes

#1502 [ACM-11543] Take port into consideration when setting custom obs url
  operators/multiclusterobservability/controllers/placementrule/hub_info_secret.go
  operators/multiclusterobservability/controllers/placementrule/hub_info_secret_test.go
Labels: lgtm, approved, dco-signoff: yes

#1505 ACM-10812: Fix status report
  collectors/metrics/pkg/forwarder/forwarder.go
  collectors/metrics/pkg/status/status.go
  collectors/metrics/pkg/status/status_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
Labels: lgtm, approved, dco-signoff: yes

#1511 Tests: Fix flaky Add_new_labels test
  proxy/pkg/util/util_test.go
Labels: lgtm, approved, dco-signoff: yes

#1507 ACM-10812: fix status update on collector
  collectors/metrics/pkg/forwarder/forwarder.go
  collectors/metrics/pkg/status/status.go
  operators/endpointmetrics/pkg/util/status.go
  operators/endpointmetrics/pkg/util/status_test.go
Labels: approved, dco-signoff: yes

#1517 Dashboards: Remove custom allValue for fleetwide
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview-optimized.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#1518 ACM-12406 - 2.10: Remove custom allValue for optimized dash
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-clusters-overview-optimized.yaml
Labels: lgtm, approved, dco-signoff: yes

#1503 Update OpenShift Virtualization overview dashboard
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-overview.yaml
Labels: approved, dco-signoff: yes, ok-to-test
