Repository stolostron/multicluster-observability-operator, pull requests merged in 2024-08, with the labels that each got.

#1557 Update ocm core setup on kind tests
  cicd-scripts/setup-e2e-tests.sh
Labels: lgtm, approved, dco-signoff: yes

#1559 [ACM-13041]Watch CMO cluster monitoring ConfigMap for changes
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1562 Update Prometheus crd after prom-operator upgrade to 0.75.2
  operators/endpointmetrics/manifests/prometheus/crd/kustomization.yaml
  operators/endpointmetrics/manifests/prometheus/crd/prometheus_crd_0_73_2.yaml
  operators/endpointmetrics/manifests/prometheus/crd/prometheus_crd_0_75_2.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-operator-deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#1548 [ACM-12909]Swap out cmo dependency for local structs
  go.mod
  go.sum
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go
  operators/multiclusterobservability/controllers/placementrule/hub_ocp_monitoring_util.go
  operators/pkg/cmo/api.go
Labels: lgtm, approved, dco-signoff: yes

#1563 [Release 2.9][ACM-12910]Swap out cmo dependency for local structs
  go.mod
  go.sum
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go
  operators/pkg/cmo/api.go
Labels: lgtm, approved, dco-signoff: yes

#1470 [release-2.12] Add support for mcoa-managed observability capabilities
  go.mod
  operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
  operators/multiclusterobservability/api/v1beta2/zz_generated.deepcopy.go
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/rbac/mco_role.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/addon_deployment_config.yaml
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_management_addon.yaml
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_role.yaml
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_role_binding.yaml
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/deployment.yaml
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/kustomization.yaml
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/service_account.yaml
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/config/resources.go
  operators/multiclusterobservability/pkg/config/resources_map.go
  operators/multiclusterobservability/pkg/rendering/renderer.go
  operators/multiclusterobservability/pkg/rendering/renderer_mcoa.go
  operators/multiclusterobservability/pkg/rendering/renderer_mcoa_test.go
  operators/multiclusterobservability/pkg/rendering/templates/templates.go
  operators/pkg/deploying/deployer.go
  operators/pkg/deploying/deployer_test.go
  tests/pkg/utils/mco_deploy.go
Labels: lgtm, approved, dco-signoff: yes, needs-ok-to-test

#1565 Fixing ACM-12888 by supplying a UID for fixed URL ref in the URL
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#1567 Remove unused limit reader struct
  collectors/metrics/pkg/reader/reader.go
Labels: lgtm, approved, dco-signoff: yes

#1574 chore: Add schedule to update Konflux files
  renovate.json
Labels: lgtm, approved, dco-signoff: yes

#1579 add `-y` to `microdnf update` to unstuck builds
  collectors/metrics/Containerfile.operator
  collectors/metrics/Dockerfile
Labels: lgtm, approved, dco-signoff: yes

#1552 rbac-query-proxy: Grafana 10/11 compatibility
  proxy/pkg/proxy/proxy.go
  proxy/pkg/proxy/proxy_test.go
Labels: lgtm, approved, dco-signoff: yes

#1582 [release-2.10] Fix dnf install to prevent interactive confirmation
  collectors/metrics/Containerfile.operator
  collectors/metrics/Dockerfile
Labels: lgtm, approved, dco-signoff: yes

#1578 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/grafana-dashboard-loader-acm-211-pull-request.yaml
  .tekton/grafana-dashboard-loader-acm-211-push.yaml
  .tekton/metrics-collector-acm-211-pull-request.yaml
  .tekton/metrics-collector-acm-211-push.yaml
  .tekton/multicluster-observability-operator-acm-211-pull-request.yaml
  .tekton/multicluster-observability-operator-acm-211-push.yaml
  .tekton/rbac-query-proxy-acm-211-pull-request.yaml
  .tekton/rbac-query-proxy-acm-211-push.yaml
Labels: dco-signoff: yes, ok-to-test

#1577 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/endpoint-monitoring-operator-acm-210-pull-request.yaml
  .tekton/endpoint-monitoring-operator-acm-210-push.yaml
  .tekton/grafana-dashboard-loader-acm-210-pull-request.yaml
  .tekton/grafana-dashboard-loader-acm-210-push.yaml
  .tekton/metrics-collector-acm-210-pull-request.yaml
  .tekton/metrics-collector-acm-210-push.yaml
  .tekton/multicluster-observability-operator-acm-210-pull-request.yaml
  .tekton/multicluster-observability-operator-acm-210-push.yaml
  .tekton/rbac-query-proxy-acm-210-pull-request.yaml
  .tekton/rbac-query-proxy-acm-210-push.yaml
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1590 Update Konflux to run on main branch
  .tekton/endpoint-monitoring-operator-acm-212-pull-request.yaml
  .tekton/grafana-dashboard-loader-acm-212-pull-request.yaml
  .tekton/metrics-collector-acm-212-pull-request.yaml
  .tekton/multicluster-observability-operator-acm-212-pull-request.yaml
  .tekton/rbac-query-proxy-acm-212-pull-request.yaml
Labels: lgtm, approved, dco-signoff: yes

#1589 ACM-12794: forward auth header to datasource
  operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
Labels: lgtm, approved, dco-signoff: yes

#1591 Expose cmo config revert binary
  operators/endpointmetrics/Containerfile.operator
  operators/endpointmetrics/Dockerfile
  operators/endpointmetrics/cmd/cmo-config-revert/main.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go
Labels: lgtm, approved, dco-signoff: yes

#1594 update MCO cluster role for imagestreams
  loaders/dashboards/Dockerfile
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/config/rbac/mco_role.yaml
  proxy/Dockerfile
Labels: approved, dco-signoff: yes

#1575 endpointmetrics: Refactor manipulations on cluster monitoring config
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config.go
Labels: lgtm, approved, dco-signoff: yes
