Repository stolostron/multicluster-observability-operator, pull requests merged in 2024-04, with the labels that each got.

#1352 [ACM-6112] Fix invalid uwl service monitors for hypershift hosted etcd and api-server
  Makefile
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_integration_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_monitoring_config_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/ocp_resource.go
  operators/endpointmetrics/controllers/observabilityendpoint/testdata/crd/clusterversions-crd.yaml
  operators/endpointmetrics/controllers/observabilityendpoint/testdata/crd/hostedclusters.hypershift.yaml
  operators/endpointmetrics/controllers/observabilityendpoint/testdata/crd/prometheusrule-crd.yaml
  operators/endpointmetrics/controllers/observabilityendpoint/testdata/crd/servicemonitor-crd.json
  operators/endpointmetrics/pkg/hypershift/hypershift.go
  operators/endpointmetrics/pkg/hypershift/hypershift_test.go
  operators/endpointmetrics/pkg/openshift/openshift.go
  operators/endpointmetrics/pkg/openshift/openshift_test.go
Labels: approved, dco-signoff: no

#1388 [ACM-10806] [2.10] Update hub collector with the whole obs addon spec
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#1393 Fix mco api beta2 import
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1391 [ACM-10743] Fix lack of reconciliation of hub's metrics collector on update of the MCO OA spec
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/main.go
Labels: lgtm, approved, dco-signoff: yes

#1394 [ACM-10811] [2.10] Fix lack of reconciliation of hub's metrics collector
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/main.go
Labels: lgtm, approved, dco-signoff: yes

#1383 Add ACM - OpenShift Virtualization Overview dashboard
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-overview.yaml
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1392 [ACM-10867]: Upgrade obs-operator to use Thanos promql engine by default
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1397 Proper registration of scheme for hub client
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/controllers/status/status_controller.go
  operators/endpointmetrics/main.go
  operators/endpointmetrics/pkg/util/client.go
  operators/endpointmetrics/pkg/util/client_test.go
Labels: lgtm, approved, dco-signoff: yes

#1398 Proper registration of scheme for hub client
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/controllers/status/status_controller.go
  operators/endpointmetrics/main.go
  operators/endpointmetrics/pkg/util/client.go
  operators/endpointmetrics/pkg/util/client_test.go
Labels: lgtm, approved, dco-signoff: yes

#1396 [ACM-10809] Fix handling of updates on AddOnDeploymentConfig
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
  operators/multiclusterobservability/main.go
Labels: lgtm, approved, dco-signoff: yes

#1402 [ACM-10987]Check SA imagePullSecret length to discard comparing against generate…
  go.mod
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#1405 [RHOBS-987] Update Thanos Compact retention
  operators/multiclusterobservability/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#1400 E2e tests
  cicd-scripts/customize-mco.sh
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/manifests/prometheus/kube-state-metrics-deployment.yaml
  operators/endpointmetrics/manifests/prometheus/node-exporter-daemonset.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-operator-role.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-resource.yaml
  operators/endpointmetrics/pkg/util/client.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  tests/pkg/tests/observability-e2e-test_suite_test.go
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/tests/observability_certrenew_test.go
  tests/pkg/tests/observability_endpoint_preserve_test.go
  tests/pkg/tests/observability_manifestwork_test.go
  tests/pkg/utils/mco_deploy.go
  tests/pkg/utils/mco_pods.go
Labels: approved, dco-signoff: yes

#1403 [ACM-10967] Stop regenerating Secrets from SA updates
  go.mod
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#1379 [ACM-10342]update metrics collector client cert when client CA is deleted
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/pkg/certificates/certificates.go
Labels: approved, dco-signoff: yes

#1407 add watch logic for endpoint sa when deleted
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#1408 [ACM-11071] Endpoint sa watch for hub - 2.10 back port
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#1412 Fix openshift-virtualization dashboard
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-openshift-virtualization-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml
Labels: lgtm, approved, dco-signoff: yes, needs-ok-to-test

#1411 E2e kind tests
  operators/endpointmetrics/pkg/rendering/renderer.go
  scripts/test-utils.sh
  tests/pkg/tests/observability_endpoint_preserve_test.go
  tests/pkg/utils/mco_clusterrolebinding.go
Labels: approved, dco-signoff: yes

#1395 ACM-10828: sort resources for microshift install
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/main.go
  operators/endpointmetrics/manifests/prometheus/prometheus-operator-role.yaml
  operators/endpointmetrics/pkg/rendering/renderer.go
  operators/endpointmetrics/pkg/rendering/renderer_test.go
  operators/multiclusterobservability/manifests/endpoint-observability/role.yaml
  operators/pkg/deploying/deployer.go
Labels: approved, dco-signoff: no

#1414 Ensure Obs API Route is reconciled correctly
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
Labels: lgtm, approved, dco-signoff: yes

#1332 [ACM-9682]Add Update Route handling for Grafana Route
  operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
  operators/multiclusterobservability/controllers/multiclusterobservability/grafana_test.go
Labels: lgtm, approved, dco-signoff: yes

#1416 [ACM-10706] Add support for custom observability hub URL
  operators/multiclusterobservability/api/shared/multiclusterobservability_shared.go
  operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/config/config_test.go
Labels: lgtm, approved, dco-signoff: yes

#1420 [ACM-10812]: fix addon status not reported in hub
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_integration_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go
  operators/endpointmetrics/controllers/status/status_controller.go
  operators/endpointmetrics/controllers/status/status_controller_integration_test.go
  operators/endpointmetrics/controllers/status/status_controller_test.go
  operators/endpointmetrics/main.go
  operators/endpointmetrics/pkg/util/client.go
  operators/endpointmetrics/pkg/util/client_test.go
  operators/endpointmetrics/pkg/util/lease.go
Labels: approved, dco-signoff: yes
