Repository stolostron/multicluster-observability-operator, pull requests merged in 2024-03, with the labels that each got.

#1319 MCO: add service monitor to alertmanager
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-accessor-serviceaccount.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-cabundle.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-clientca-metric.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-clusterrole.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-config.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-kube-rbac-proxy-metric.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-operated.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-proxy.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-service-metrics.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-service.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-serviceaccount.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-servicemonitor.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/alertmanager-statefulset.yaml
  operators/multiclusterobservability/manifests/base/alertmanager/kustomization.yaml
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/rendering/renderer.go
  operators/multiclusterobservability/pkg/rendering/renderer_alertmanager.go
  operators/multiclusterobservability/pkg/rendering/renderer_alertmanager_test.go
  operators/multiclusterobservability/pkg/rendering/renderer_test.go
  tests/run-in-kind/req_crds/servicemonitor-crd.json
Labels: approved, dco-signoff: no

#1359 Kind version
  .gitignore
  Makefile
  cicd-scripts/customize-mco.sh
  cicd-scripts/run-e2e-in-kind-via-prow.sh
  cicd-scripts/setup-e2e-tests.sh
  scripts/install-binaries.sh
  scripts/test-utils.sh
  tests/run-in-kind/run-e2e-in-kind.sh
Labels: lgtm, approved, dco-signoff: yes

#1361 Add make target for collector integration tests and docs cleanup
  Makefile
  collectors/metrics/README.md
  collectors/metrics/test/integration/prereq.sh
  operators/multiclusterobservability/pkg/rendering/renderer_alertmanager_test.go
  scripts/install-binaries.sh
Labels: lgtm, approved, dco-signoff: yes

#1362 Bring the Route and Route RBAC up to date
  tests/run-in-kind/router/route_crd.yaml
  tests/run-in-kind/router/router_rbac.yaml
Labels: lgtm, approved, dco-signoff: yes

#1366 Update hub metrics collection resources when modified
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
Labels: lgtm, approved, dco-signoff: yes

#1368 Create a Secret for Grafana Accessor SA if not auto-generated
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#1367 [ACM-10234]Create a Secret for Grafana Accessor SA if not auto-generated
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
Labels: lgtm, do-not-merge/hold, approved, dco-signoff: yes

#1370 [ACM 10232, 10274] Keep managedclusteraddon for local-cluster
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1372 [ACM-10153] Ensure create/update for all resource types in hub metrics collection
  operators/multiclusterobservability/controllers/placementrule/endpoint_metrics_operator.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#1365 e2e testing changes
  DEVELOPMENT.md
  Makefile
  cicd-scripts/customize-mco.sh
  cicd-scripts/run-e2e-in-kind-via-prow.sh
  cicd-scripts/run-e2e-tests.sh
  cicd-scripts/setup-e2e-tests.sh
  operators/multiclusterobservability/Dockerfile.dev
  scripts/bootstrap-kind-env.sh
  scripts/test-utils.sh
  tests/pkg/tests/observability_install_test.go
  tests/pkg/utils/utils.go
Labels: lgtm, approved, dco-signoff: yes

#1373 [ACM-10261] Create a Secret for Grafana Accessor SA if not auto-generated
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
Labels: lgtm, approved, dco-signoff: yes

#1374 Fix CI lint
  .github/workflows/lint.yaml
  collectors/metrics/pkg/forwarder/forwarder.go
  collectors/metrics/pkg/metricsclient/metricsclient.go
Labels: lgtm, approved, dco-signoff: yes

#1378 Update sonar properties
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes

#1380 Sonarcloud properties: fix typo
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes

#1385 [ACM-10506]endpointmetrics: Do not add generated resources as volumes on ocp3
  operators/endpointmetrics/controllers/observabilityendpoint/match_evaluator_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1384 [ACM-10506]endpointmetrics: Do not add generated resources as volumes on ocp3 cl…
  operators/endpointmetrics/controllers/observabilityendpoint/match_evaluator_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1386 [ACM-10511] Update hub collector with the whole obs addon spec
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#1389 [2.10] [ACM-10406] Fix handling of updates on AddOnDeploymentConfig
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
  operators/multiclusterobservability/main.go
Labels: lgtm, approved, dco-signoff: yes

#1390 [ACM-10511] Improve robustness when listing MCO CRs from the collector
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
Labels: lgtm, approved, dco-signoff: yes
