Repository stolostron/multicluster-observability-operator, pull requests merged in 2024-02, with the labels that each got.

#1313 ACM-9018: Add hosted control plane overview and resources dashboards
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-hcp-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-resources-hcp.yaml
Labels: lgtm, approved, dco-signoff: yes

#1314 First drop: Hub metrics collector feature
  operators/endpointmetrics/pkg/util/client.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
Labels: approved, dco-signoff: yes

#1316 Hub metrics collector feature
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: approved, dco-signoff: no

#1317 Hub metrics collector feature
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/main.go
Labels: approved, dco-signoff: no

#1312 [ACM-9321] Stop firing IngressWithoutClassName alert
  operators/multiclusterobservability/manifests/base/proxy/ingress.yaml
Labels: lgtm, approved, dco-signoff: yes

#1323 alert: make ACMRemoteWriteError less prone to flakes/flapping
  operators/multiclusterobservability/manifests/base/alertmanager/prometheusrule.yaml
Labels: lgtm, approved, dco-signoff: yes

#1324 Fix HCP dashboards
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-hcp-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml
Labels: lgtm, approved, dco-signoff: yes

#1328 fix a metric query to use instant value
  operators/multiclusterobservability/manifests/base/grafana/dash-acm-hcp-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#1331 Add Ingress update function to template deployer
  operators/pkg/deploying/deployer.go
  operators/pkg/deploying/deployer_test.go
Labels: lgtm, approved, dco-signoff: yes

#1329 [ACM-8543] Tag Observatorium CR with a hash of all the config it uses
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
Labels: lgtm, approved, dco-signoff: yes

#1315 First drop: Hub metrics collector feature (#1314)
  operators/endpointmetrics/pkg/util/client.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: needs-rebase, do-not-merge/hold, approved, dco-signoff: yes

#1338 Revert "Merge branch 'hub-metrics-collector' into main"
  operators/endpointmetrics/pkg/util/client.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: approved, dco-signoff: yes

#1339 Hub Metrics Collection
  collectors/metrics/pkg/metricsclient/metricsclient.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/controllers/observabilityendpoint/predicate_func.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
  operators/multiclusterobservability/pkg/certificates/cert_agent.go
  operators/multiclusterobservability/pkg/certificates/signer.go
  operators/multiclusterobservability/pkg/certificates/signer_test.go
  operators/pkg/config/config.go
Labels: approved, dco-signoff: no

#1310 Adjust server timeouts to align with default Grafana settings
  collectors/metrics/test/integration/manifests/observatorium-api.yaml
Labels: lgtm, approved, dco-signoff: yes

#1334 [ACM-8543] Fix reconciliation on Observatorium CR for update scenario
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
  operators/multiclusterobservability/pkg/certificates/cert_controller.go
  tests/pkg/tests/observability_certrenew_test.go
Labels: lgtm, approved, dco-signoff: yes

#1342 improve ci logging
  cicd-scripts/run-e2e-tests.sh
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/tests/observability_install_test.go
  tests/pkg/utils/client.go
  tests/pkg/utils/mco_deploy.go
  tests/pkg/utils/mco_oba.go
  tests/pkg/utils/utils.go
Labels: lgtm, approved, dco-signoff: yes

#1330 [ACM-9653] Updating prometheus-k8s CRD's to 0.68
  cicd-scripts/customize-mco.sh
  operators/endpointmetrics/manifests/prometheus/crd/kustomization.yaml
  operators/endpointmetrics/manifests/prometheus/crd/prometheus_crd_0_53_1.yaml
  operators/endpointmetrics/manifests/prometheus/crd/prometheus_crd_0_68_0.yaml
  operators/endpointmetrics/manifests/prometheus/prometheus-operator-deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#1340 Hub metrics collector feature
  cicd-scripts/run-e2e-tests.sh
  collectors/metrics/pkg/forwarder/forwarder.go
  collectors/metrics/pkg/metricsclient/metricsclient.go
  go.mod
  go.sum
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller_test.go
  operators/endpointmetrics/controllers/observabilityendpoint/predicate_func.go
  operators/endpointmetrics/main.go
  operators/endpointmetrics/pkg/util/client.go
  operators/endpointmetrics/pkg/util/status.go
  operators/endpointmetrics/pkg/util/status_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/placementrule/hub_ocp_monitoring_util.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/controllers/placementrule/obsaddon.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
  operators/multiclusterobservability/pkg/certificates/cert_agent.go
  operators/multiclusterobservability/pkg/certificates/cert_controller.go
  operators/multiclusterobservability/pkg/certificates/certificates.go
  operators/multiclusterobservability/pkg/certificates/signer.go
  operators/multiclusterobservability/pkg/certificates/signer_test.go
  operators/multiclusterobservability/pkg/config/config.go
  operators/pkg/config/config.go
  operators/pkg/deploying/deployer.go
  tests/pkg/utils/mco_oba.go
  tests/run-in-kind/req_crds/servicemonitor-crd.json
Labels: approved, dco-signoff: yes

#1353 Add documentation and targets to help build project locally for macOS
  .github/workflows/lint.yaml
  .gitignore
  DEVELOPMENT.md
  Makefile
  cicd-scripts/install-dependencies.sh
  cicd-scripts/update-check-mco-csv.sh
  operators/multiclusterobservability/bundle.Dockerfile
  scripts/install-binaries.sh
Labels: approved, dco-signoff: yes

#1360 Cleanup some unused code and docs tidy
  cicd-scripts/build.sh
  cicd-scripts/run-unit-tests.sh
  collectors/metrics/test/integration/setup.sh
  tools/simulator/README.md
  tools/simulator/managed-cluster/README.md
  tools/simulator/managed-cluster/setup-managedcluster.sh
Labels: lgtm, approved, dco-signoff: yes
