Repository stolostron/multicluster-observability-operator, pull requests merged in 2024-01, with the labels that each got.

#1300 Set GOFLAGS to empty string for RHTAP builds
  collectors/metrics/Containerfile.operator
  loaders/dashboards/Containerfile.operator
  operators/endpointmetrics/Containerfile.operator
  operators/multiclusterobservability/Containerfile.operator
  proxy/Containerfile.operator
  tools/simulator/alert-forward/Containerfile.operator
Labels: lgtm, approved, dco-signoff: yes

#1289 add watch logic for addondeployment
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: approved, dco-signoff: yes

#1293 Add support for custom proxy ca
  collectors/metrics/pkg/forwarder/forwarder_test.go
  collectors/metrics/pkg/metricsclient/metricsclient.go
  collectors/metrics/testdata/tls/custom_ca.crt
  go.mod
  go.sum
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
Labels: lgtm, approved, dco-signoff: yes

#1302 [release-2.9] Add support for custom proxy ca (#1293)
  collectors/metrics/pkg/forwarder/forwarder_test.go
  collectors/metrics/pkg/metricsclient/metricsclient.go
  collectors/metrics/testdata/tls/custom_ca.crt
  go.mod
  go.sum
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector.go
  operators/endpointmetrics/controllers/observabilityendpoint/metrics_collector_test.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
Labels: lgtm, approved, dco-signoff: yes

#1301 [release-2.9] add watch logic for addondeployment (#1289)
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func_test.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#1265 [ACM-8259] fix mco status update race condition
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_status.go
Labels: lgtm, approved, dco-signoff: yes

#1305 Owners: Add full MultiCluster Observability Team
  OWNERS
Labels: lgtm, approved, dco-signoff: yes

#1303 Update MCO CRDs
  operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
Labels: lgtm, dco-signoff: yes

#1304 Change datasource timeout config for Grafana and add matching timeout…
  operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
Labels: lgtm, approved, dco-signoff: yes

#1308 Change datasource timeout config for Grafana and add matching timeout…
  operators/multiclusterobservability/controllers/multiclusterobservability/grafana.go
Labels: lgtm, approved, dco-signoff: yes
