Repository stolostron/multicluster-observability-operator, pull requests merged in 2025-05, with the labels that each got.

#1986 Grafana: Remove OCP 3.11 dashboards
  examples/export/victoriametrics.yaml
  operators/endpointmetrics/pkg/collector/metrics_collector.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml
  operators/multiclusterobservability/manifests/base/grafana/ocp311/dash-acm-clusters-overview-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/ocp311/dash-acm-optimization-overview-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/ocp311/dash-k8s-capacity-planning-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/ocp311/dash-k8s-compute-resources-namespace-pods-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/ocp311/dash-k8s-compute-resources-pod-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/ocp311/dash-k8s-namespaces-in-cluster-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/ocp311/dash-k8s-pods-in-namespace-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/ocp311/dash-k8s-summary-by-node-ocp311.yaml
  operators/multiclusterobservability/manifests/base/grafana/ocp311/kustomization.yaml
  operators/pkg/util/allowlist.go
  operators/pkg/util/allowlist_test.go
Labels: lgtm, approved, dco-signoff: yes

#1987 Update Konflux Tasks
  .tekton/endpoint-monitoring-operator-acm-214-pull-request.yaml
  .tekton/endpoint-monitoring-operator-acm-214-push.yaml
  .tekton/grafana-dashboard-loader-acm-214-pull-request.yaml
  .tekton/grafana-dashboard-loader-acm-214-push.yaml
  .tekton/metrics-collector-acm-214-pull-request.yaml
  .tekton/metrics-collector-acm-214-push.yaml
  .tekton/multicluster-observability-operator-acm-214-pull-request.yaml
  .tekton/multicluster-observability-operator-acm-214-push.yaml
  .tekton/rbac-query-proxy-acm-214-pull-request.yaml
  .tekton/rbac-query-proxy-acm-214-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#1991 ACM-15008: Updated the descriptions in ACM HCP overview dashboard
  operators/multiclusterobservability/manifests/base/grafana/hcp/dash-acm-hcp-overview.yaml
Labels: lgtm, approved, dco-signoff: yes

#1984 [MCOA]: Update default stack management
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_role.yaml
  operators/multiclusterobservability/pkg/rendering/renderer_mcoa.go
  operators/multiclusterobservability/pkg/rendering/renderer_mcoa_test.go
Labels: lgtm, approved, dco-signoff: yes

#2001 Improve MultiClusterObservability debuggability
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
Labels: lgtm, approved, dco-signoff: yes

#2004 Add metrics exceptions for virt dashboards
  cicd-scripts/metrics/Makefile
Labels: lgtm, approved, dco-signoff: yes

#2003 Tests: pin victoria metrics image
  examples/export/victoriametrics.yaml
Labels: approved, dco-signoff: yes

#1863 Update the CNV time in status dashboard
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-virtual-machines-by-time-in-status.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/scrape-config.yaml
Labels: lgtm, approved, dco-signoff: yes

#1935 Add Virtual Machines Service Level dashboard
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-virtual-machines-service-level.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/kustomization.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/scrape-config.yaml
Labels: lgtm, approved, dco-signoff: yes

#2010 Remove exception for kubevirt PRs
  cicd-scripts/metrics/Makefile
Labels: lgtm, approved, dco-signoff: yes

#1864 Update CNV single cluster view dashboard
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-openshift-virtualization-single-cluster-view.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/scrape-config.yaml
Labels: approved, dco-signoff: yes

#1862 Update virtual machines inventory dashboard
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-virtual-machines-inventory.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/scrape-config.yaml
Labels: dco-signoff: yes

#1866 Update CNV clusters overview
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-openshift-virtualization-overview.yaml
Labels: approved, dco-signoff: yes

#2011 Fix kubevirt dashboards and metrics
  cicd-scripts/metrics/Makefile
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/dash-acm-openshift-virtualization-single-vm-view.yaml
  operators/multiclusterobservability/manifests/base/grafana/virtualization/scrape-config.yaml
Labels: lgtm, approved, dco-signoff: yes

#2009 Improve some e2e
  tests/pkg/tests/observability_metrics_test.go
  tests/pkg/utils/mco_deploy.go
Labels: lgtm, approved, dco-signoff: yes

#2014 e2e: Do not replace object-storage secret with *
  tests/pkg/utils/mco_deploy.go
Labels: lgtm, approved, dco-signoff: yes

#1806 OBSINTA-203: Grafana dashboard for Incidents overview
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/platform-mcoa/dash-acm-incidents-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/platform-mcoa/kustomization.yaml
  operators/multiclusterobservability/manifests/base/grafana/platform-mcoa/scrape-config.yaml
  operators/multiclusterobservability/manifests/base/grafana/platform/dash-acm-incidents-overview.yaml
  operators/multiclusterobservability/manifests/base/grafana/platform/kustomization.yaml
Labels: lgtm, approved, dco-signoff: yes

#2017 rbac_test: correct login to kube:admin+cleanup env
  tests/pkg/tests/observability_rbac_test.go
  tests/setup_rbac_test.sh
Labels: lgtm, approved, dco-signoff: yes

#2018 Fix CI metrics check
  cicd-scripts/metrics/Makefile
  cicd-scripts/metrics/cmd/rulescheck/main.go
Labels: lgtm, approved, dco-signoff: yes

#1983 [Release-2.14] update addon-framework to v0.12.0
  go.mod
  go.sum
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/config/rbac/mco_role.yaml
  operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
  operators/multiclusterobservability/pkg/util/clustermanagementaddon_test.go
Labels: lgtm, approved, dco-signoff: yes

#1936 [ACM-17966] Namespace right sizing recommendation changes
  go.mod
  go.sum
  operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
  operators/multiclusterobservability/api/v1beta2/zz_generated.deepcopy.go
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/rbac/mco_role.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_controller_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_helper.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_helper_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_configmap.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_configmap_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_helper.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_helper_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_placement.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_placement_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_placementbinding.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_placementbinding_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_policy.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_policy_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_prometheusrule.go
  operators/multiclusterobservability/controllers/multiclusterobservability/analytics/rightsizing_namespace_prometheusrule_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_test.go
  operators/multiclusterobservability/main.go
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  operators/multiclusterobservability/manifests/base/grafana/analytics/dash-acm-right-sizing-namespace.yaml
  operators/multiclusterobservability/manifests/base/grafana/analytics/kustomization.yaml
  operators/multiclusterobservability/manifests/base/grafana/analytics/scrape-config.yaml
  operators/multiclusterobservability/manifests/base/grafana/kustomization.yaml
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#2021 Tests: Skip watchdog alert on *ks on missing login
  tests/pkg/tests/observability_alert_test.go
Labels: lgtm, approved, dco-signoff: yes

#2026 fix CMOWatcher unit test flake
  operators/endpointmetrics/pkg/openshift/cmowatcher_test.go
Labels: lgtm, approved, dco-signoff: yes

#2028 Retriggering image rebuild
  README.md
Labels: approved, dco-signoff: yes

#2022 Tests: skip RHACM4K-7518 if no managed cluster
  tests/pkg/tests/observability_addon_test.go
Labels: lgtm, approved, dco-signoff: yes
