Repository stolostron/multicluster-observability-operator, pull requests merged in 2025-04, with the labels that each got.

#1928 upgrade x/crypto and x/oauth2
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1929 [Release-2.13]: Upgrade x/crypto and x/oauth2
  .bingo/Variables.mk
  .bingo/faillint.mod
  .bingo/faillint.sum
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/variables.env
  .github/workflows/lint.yaml
  .golangci.yml
  collectors/metrics/Containerfile.operator
  go.mod
  go.sum
  loaders/dashboards/Containerfile.operator
  operators/endpointmetrics/Containerfile.operator
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/multiclusterobservability/Containerfile.operator
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/placementrule/status.go
  proxy/Containerfile.operator
  tests/Containerfile.operator
  tools/simulator/alert-forward/Containerfile.operator
  tools/simulator/metrics-collector/metrics-extractor/Containerfile.operator
Labels: lgtm, approved, dco-signoff: yes

#1834 Manage deployment of resources for MCOA and metrics collector
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/placementrule/endpoint_metrics_operator.go
  operators/multiclusterobservability/controllers/placementrule/hub_ocp_monitoring_util.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork.go
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/controllers/placementrule/obsaddon.go
  operators/multiclusterobservability/controllers/placementrule/obsaddon_test.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
  operators/multiclusterobservability/controllers/placementrule/predicate_func.go
  operators/multiclusterobservability/controllers/placementrule/role.go
  operators/multiclusterobservability/controllers/placementrule/role_test.go
  operators/multiclusterobservability/pkg/certificates/cert_agent.go
  operators/multiclusterobservability/pkg/certificates/certificates.go
  operators/multiclusterobservability/pkg/certificates/signer.go
  operators/multiclusterobservability/pkg/certificates/signer_test.go
  operators/multiclusterobservability/pkg/util/clustermanagementaddon.go
  operators/multiclusterobservability/pkg/util/clustermanagementaddon_test.go
Labels: lgtm, approved, dco-signoff: yes

#1933 Add new SAST tasks to Konflux pipelines
  .tekton/endpoint-monitoring-operator-acm-214-pull-request.yaml
  .tekton/endpoint-monitoring-operator-acm-214-push.yaml
  .tekton/grafana-dashboard-loader-acm-214-pull-request.yaml
  .tekton/grafana-dashboard-loader-acm-214-push.yaml
  .tekton/metrics-collector-acm-214-pull-request.yaml
  .tekton/metrics-collector-acm-214-push.yaml
  .tekton/multicluster-observability-operator-acm-214-pull-request.yaml
  .tekton/multicluster-observability-operator-acm-214-push.yaml
  .tekton/rbac-query-proxy-acm-214-pull-request.yaml
  .tekton/rbac-query-proxy-acm-214-push.yaml
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1912 [ACM-15724] Observability - RBAC - Verify only cluster-manager-admin role can deploy MCO CR
  tests/pkg/tests/observability_rbac_test.go
  tests/pkg/utils/utils.go
  tests/setup_rbac_test.sh
Labels: approved, dco-signoff: yes

#1939 Automerge Konlfux updates
  renovate.json
Labels: approved, dco-signoff: no

#1941 [ACM-19970] Make sure detached cluster is cleaned up
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1944 [Release-2.11]: Fix CVE-2025-30204
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1931 [Release-2.11]: Upgrade x/crypto and x/oauth2
  .bingo/Variables.mk
  .bingo/controller-gen.mod
  .bingo/controller-gen.sum
  .bingo/faillint.mod
  .bingo/faillint.sum
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/operator-sdk.mod
  .bingo/variables.env
  .github/workflows/lint.yaml
  .golangci.yml
  Makefile
  collectors/metrics/Containerfile.operator
  collectors/metrics/Dockerfile
  go.mod
  go.sum
  loaders/dashboards/Containerfile.operator
  loaders/dashboards/Dockerfile
  operators/endpointmetrics/Containerfile.operator
  operators/endpointmetrics/Dockerfile
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/multiclusterobservability/Containerfile.operator
  operators/multiclusterobservability/Dockerfile
  operators/multiclusterobservability/Makefile
  operators/multiclusterobservability/PROJECT
  operators/multiclusterobservability/bundle.Dockerfile
  operators/multiclusterobservability/bundle/manifests/core.observatorium.io_observatoria.yaml
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_observabilityaddons.yaml
  operators/multiclusterobservability/bundle/metadata/annotations.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_observabilityaddons.yaml
  operators/multiclusterobservability/config/manifests/bases/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/config/rbac/role.yaml
  operators/multiclusterobservability/config/webhook/manifests.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/placementrule/status.go
  proxy/Containerfile.operator
  proxy/Dockerfile
  tests/Containerfile.operator
  tests/Dockerfile
  tools/simulator/alert-forward/Containerfile.operator
  tools/simulator/alert-forward/Dockerfile
  tools/simulator/metrics-collector/metrics-extractor/Containerfile.operator
  tools/simulator/metrics-collector/metrics-extractor/Dockerfile
Labels: lgtm, approved, dco-signoff: yes

#1945 [Fix]: filter out non standard condition types when replicating addon status conditions
  operators/multiclusterobservability/controllers/placementrule/status.go
  operators/multiclusterobservability/controllers/placementrule/status_test.go
Labels: lgtm, approved, dco-signoff: yes

#1943 [Main] upgrade jwt
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1952 Tests: Make JUnit report conform to QE standard
  Jenkinsfile
  tests/pkg/tests/observability-e2e-test_suite_test.go
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/tests/observability_alert_test.go
  tests/pkg/tests/observability_certrenew_test.go
  tests/pkg/tests/observability_config_test.go
  tests/pkg/tests/observability_dashboard_test.go
  tests/pkg/tests/observability_endpoint_preserve_test.go
  tests/pkg/tests/observability_export_test.go
  tests/pkg/tests/observability_grafana_dev_test.go
  tests/pkg/tests/observability_grafana_test.go
  tests/pkg/tests/observability_manifestwork_test.go
  tests/pkg/tests/observability_metrics_test.go
  tests/pkg/tests/observability_observatorium_preserve_test.go
  tests/pkg/tests/observability_rbac_test.go
  tests/pkg/tests/observability_reconcile_test.go
  tests/pkg/tests/observability_retention_test.go
  tests/pkg/tests/observability_route_test.go
Labels: lgtm, approved, dco-signoff: yes

#1948 ACM-18751: add a new attribute for Incident Detection to the MCO CR
  operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
  operators/multiclusterobservability/api/v1beta2/zz_generated.deepcopy.go
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/pkg/rendering/renderer_mcoa.go
Labels: lgtm, approved, dco-signoff: yes

#1949 Remove Bearer from authorization header when setting X-Forwarded-Access-Token
  proxy/pkg/proxy/proxy.go
  proxy/pkg/proxy/proxy_test.go
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1940 remove local cluster naming dependency
  cicd-scripts/setup-e2e-tests.sh
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller.go
  tests/pkg/tests/observability_grafana_test.go
  tests/pkg/utils/mco_deploy.go
  tests/pkg/utils/mco_managedcluster.go
  tests/pkg/utils/mco_oba.go
Labels: lgtm, approved, dco-signoff: yes

#1953 fix: use correct CRD values for MCOA
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_management_addon.yaml
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/config/config_test.go
  operators/multiclusterobservability/pkg/rendering/renderer_mcoa.go
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1954 [release-2.13] Tests: Make JUnit report conform to QE standard
  Jenkinsfile
  tests/pkg/tests/observability-e2e-test_suite_test.go
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/tests/observability_alert_test.go
  tests/pkg/tests/observability_certrenew_test.go
  tests/pkg/tests/observability_config_test.go
  tests/pkg/tests/observability_dashboard_test.go
  tests/pkg/tests/observability_endpoint_preserve_test.go
  tests/pkg/tests/observability_export_test.go
  tests/pkg/tests/observability_grafana_dev_test.go
  tests/pkg/tests/observability_grafana_test.go
  tests/pkg/tests/observability_manifestwork_test.go
  tests/pkg/tests/observability_metrics_test.go
  tests/pkg/tests/observability_observatorium_preserve_test.go
  tests/pkg/tests/observability_reconcile_test.go
  tests/pkg/tests/observability_retention_test.go
  tests/pkg/tests/observability_route_test.go
Labels: lgtm, approved, dco-signoff: yes

#1982 fix: add rbac permission to allow MCOA to get Subscriptions on hub
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_role.yaml
Labels: lgtm, approved, dco-signoff: yes
