Repository stolostron/multicluster-observability-operator, pull requests merged in 2025-01, with the labels that each got.

#1746 Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1748 [release-2.10] Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1749 [release-2.11] Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1734 [release-2.12] Fix leaky goroutine on metrics-collector (#1733)
  collectors/metrics/cmd/metrics-collector/main.go
  collectors/metrics/cmd/metrics-collector/main_test.go
Labels: lgtm, approved, dco-signoff: yes

#1761 [release-2.11] Revert non-CVE changes
  collectors/metrics/pkg/metricsclient/metricsclient.go
  collectors/metrics/pkg/metricsclient/metricsclient_test.go
  go.mod
  go.sum
  operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
  operators/multiclusterobservability/controllers/placementrule/predict_func.go
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/config/config_test.go
Labels: lgtm, approved, dco-signoff: yes

#1762 [release-2.9] Bump x/net and x/crypto
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#1760 enable hermetic builds
  .tekton/endpoint-monitoring-operator-acm-213-pull-request.yaml
  .tekton/endpoint-monitoring-operator-acm-213-push.yaml
  .tekton/grafana-dashboard-loader-acm-213-pull-request.yaml
  .tekton/grafana-dashboard-loader-acm-213-push.yaml
  .tekton/metrics-collector-acm-213-pull-request.yaml
  .tekton/metrics-collector-acm-213-push.yaml
  .tekton/multicluster-observability-operator-acm-213-pull-request.yaml
  .tekton/multicluster-observability-operator-acm-213-push.yaml
  .tekton/rbac-query-proxy-acm-213-pull-request.yaml
  .tekton/rbac-query-proxy-acm-213-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#1659 ACM-14962: init MCOA metrics
  operators/multiclusterobservability/api/v1beta2/multiclusterobservability_types.go
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_management_addon.yaml
  operators/multiclusterobservability/manifests/base/multicluster-observability-addon/cluster_role.yaml
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/config/config_test.go
  operators/multiclusterobservability/pkg/rendering/renderer_mcoa.go
  operators/multiclusterobservability/pkg/rendering/renderer_mcoa_test.go
Labels: lgtm, approved, dco-signoff: yes

#1777 Fix: Flapping addon staus due to 409 response on remote write to the hub
  collectors/metrics/pkg/forwarder/forwarder.go
  collectors/metrics/pkg/metricsclient/metricsclient.go
  collectors/metrics/pkg/metricsclient/metricsclient_test.go
Labels: approved, dco-signoff: yes

#1778 Fix: Deduplicate the __name__ label in the metrics collector
  collectors/metrics/pkg/metricsclient/metricsclient.go
  collectors/metrics/pkg/metricsclient/metricsclient_test.go
Labels: approved, dco-signoff: yes

#1763 minor update of README and Makefile
  Makefile
  README.md
Labels: lgtm, approved, dco-signoff: yes

#1794 Fix grafana dashboards update when adding new folder
  operators/endpointmetrics/pkg/collector/metrics_collector.go
  operators/multiclusterobservability/manifests/base/grafana/deployment.yaml
  operators/multiclusterobservability/pkg/certificates/cert_controller.go
  operators/pkg/util/util.go
Labels: lgtm, approved, dco-signoff: yes

#1801 Update renovate.json to pick only main and actual release branches
  renovate.json
Labels: lgtm, approved, dco-signoff: yes

#1803 Fix flaky symlink creation in placement unit tests
  operators/multiclusterobservability/controllers/placementrule/manifestwork_test.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#1805 Fix e2e watchdog alert test
  go.mod
  go.sum
  tests/pkg/tests/observability_alert_test.go
  tests/pkg/utils/mco_managedcluster.go
Labels: approved, dco-signoff: no

#1796 ACM-15764: fix access token renewal from the metrics collector
  collectors/metrics/pkg/forwarder/forwarder.go
  collectors/metrics/pkg/forwarder/token.go
  collectors/metrics/pkg/forwarder/token_test.go
  collectors/metrics/pkg/http/roundtripper.go
  go.mod
Labels: lgtm, approved, dco-signoff: yes

#1810 [Backport 2.12] ACM-15764: fix access token renewal from the metrics collector (#1796)
  collectors/metrics/pkg/forwarder/forwarder.go
  collectors/metrics/pkg/forwarder/token.go
  collectors/metrics/pkg/forwarder/token_test.go
  collectors/metrics/pkg/http/roundtripper.go
  go.mod
Labels: lgtm, approved, dco-signoff: yes

#1802 Add support for grafana folder in generate-dashboard-configmap-yaml script
  tests/grafana-dev-test.sh
  tools/generate-dashboard-configmap-yaml.sh
  tools/setup-grafana-dev.sh
Labels: lgtm, approved, dco-signoff: yes
