Repository stolostron/multicluster-observability-operator, pull requests merged in 2025-03, with the labels that each got.

#1861 Update go builder - 1.23
  collectors/metrics/Containerfile.operator
  collectors/metrics/Dockerfile
  loaders/dashboards/Containerfile.operator
  loaders/dashboards/Dockerfile
  operators/endpointmetrics/Containerfile.operator
  operators/endpointmetrics/Dockerfile
  operators/multiclusterobservability/Containerfile.operator
  operators/multiclusterobservability/Dockerfile
  proxy/Containerfile.operator
  proxy/Dockerfile
  tests/Containerfile.operator
  tests/Dockerfile
  tools/simulator/alert-forward/Containerfile.operator
  tools/simulator/alert-forward/Dockerfile
  tools/simulator/metrics-collector/metrics-extractor/Containerfile.operator
  tools/simulator/metrics-collector/metrics-extractor/Dockerfile
Labels: approved, dco-signoff: yes, ok-to-test

#1886 dashboard-loader: set home dashboard with UID
  loaders/dashboards/pkg/controller/dashboard_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1897 [ACM-17443] Check for node selector addondeployment config in endpoint operator
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#1891 Add envtest to verify that MCO alerts are created for CMO on the hub
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller_integration_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/testdata/crd/addon.open-cluster-management.io_addondeploymentconfigs.crd.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/testdata/crd/addon.open-cluster-management.io_clustermanagementaddons.crd.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/testdata/crd/monitoring.coreos.com_prometheusrules.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/testdata/crd/monitoring.coreos.com_servicemonitors.yaml
  operators/multiclusterobservability/controllers/multiclusterobservability/testdata/crd/routes-Default.crd.yaml
Labels: lgtm, approved, dco-signoff: yes

#1899 Only activate cmowatcher on spokes
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/main.go
Labels: lgtm, approved, dco-signoff: yes

#1892 Add controller reference on resources deployed by the endpoint-operator
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/endpointmetrics/pkg/collector/metrics_collector.go
  operators/endpointmetrics/pkg/collector/metrics_collector_test.go
  operators/multiclusterobservability/manifests/endpoint-observability/role.yaml
Labels: lgtm, approved, dco-signoff: yes

#1898 Tests: Don't check that ignoredMetrics is in sync
  tests/pkg/tests/observability_metrics_test.go
Labels: lgtm, approved, dco-signoff: yes

#1903 cherry pick to 2.10 for ACM-15167
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium_test.go
  operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func.go
  operators/multiclusterobservability/pkg/config/config.go
Labels: lgtm, approved, dco-signoff: yes

#1888 Remove standard hub rules for MCOA
  Makefile
  cicd-scripts/metrics/Makefile
  cicd-scripts/metrics/cmd/rulescheck/main.go
  cicd-scripts/metrics/internal/rule/rule.go
  operators/multiclusterobservability/controllers/multiclusterobservability/observatorium.go
  operators/multiclusterobservability/manifests/base/grafana/platform-mcoa/prometheus-rule.yaml
  operators/multiclusterobservability/manifests/base/grafana/platform-mcoa/scrape-config.yaml
Labels: lgtm, approved, dco-signoff: yes

#1890 [ACM-15722] RBAC e2e only authorized user can query managed cluster metrics data
  DEVELOPMENT.md
  cicd-scripts/customize-mco.sh
  examples/mco/e2e/v1beta1/observability-v1beta1-to-v1beta2-golden.yaml
  examples/mco/e2e/v1beta1/observability.yaml
  examples/mco/e2e/v1beta2/custom-certs-kind/kustomization.yaml
  examples/mco/e2e/v1beta2/custom-certs-kind/observability.yaml
  operators/multiclusterobservability/pkg/config/config.go
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/tests/observability_alert_test.go
  tests/pkg/tests/observability_certrenew_test.go
  tests/pkg/tests/observability_config_test.go
  tests/pkg/tests/observability_dashboard_test.go
  tests/pkg/tests/observability_deployment_test.go
  tests/pkg/tests/observability_endpoint_preserve_test.go
  tests/pkg/tests/observability_export_test.go
  tests/pkg/tests/observability_grafana_dev_test.go
  tests/pkg/tests/observability_grafana_test.go
  tests/pkg/tests/observability_install_test.go
  tests/pkg/tests/observability_manifestwork_test.go
  tests/pkg/tests/observability_metrics_test.go
  tests/pkg/tests/observability_observatorium_preserve_test.go
  tests/pkg/tests/observability_rbac_test.go
  tests/pkg/tests/observability_reconcile_test.go
  tests/pkg/tests/observability_retention_test.go
  tests/pkg/tests/observability_route_test.go
  tests/pkg/utils/mco_deploy.go
  tests/pkg/utils/mco_deployments.go
  tests/pkg/utils/mco_metric.go
  tests/pkg/utils/utils.go
  tests/setup_rbac_test.sh
Labels: approved, dco-signoff: yes

#1919 Remove caBundle from injection patch
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/patches/webhook_multiclusterobservabilities_cainjection_patch.yaml
Labels: lgtm, approved, dco-signoff: yes

#1920 Remove caBundle from injection patch
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/bundle/manifests/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  operators/multiclusterobservability/config/crd/patches/webhook_multiclusterobservabilities_cainjection_patch.yaml
Labels: lgtm, approved, dco-signoff: yes

#1922 [2.13] Correctly fix limit removal
  .github/workflows/lint.yaml
  operators/multiclusterobservability/config/manager/manager.yaml
Labels: lgtm, approved, dco-signoff: yes

#1921 Linter fixes
  .github/workflows/lint.yaml
  operators/multiclusterobservability/config/manager/manager.yaml
  tests/pkg/utils/utils.go
Labels: lgtm, approved, dco-signoff: yes

#1930 [Release-2.12]: Upgrade x/crypto and x/oauth2
  .bingo/Variables.mk
  .bingo/faillint.mod
  .bingo/faillint.sum
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/variables.env
  .github/workflows/lint.yaml
  .golangci.yml
  go.mod
  go.sum
  operators/endpointmetrics/controllers/observabilityendpoint/observabilityaddon_controller.go
  operators/multiclusterobservability/controllers/multiclusterobservability/multiclusterobservability_controller.go
  operators/multiclusterobservability/controllers/placementrule/status.go
Labels: lgtm, approved, dco-signoff: yes
