Repository stolostron/multicluster-observability-operator, pull requests merged in 2025-02, with the labels that each got.

#1820 Fix: list of managedClusters in e2e tests for AlertManager
  tests/pkg/tests/observability_alert_test.go
  tests/pkg/utils/kube_debug.go
  tests/pkg/utils/mco_managedcluster.go
Labels: lgtm, approved, dco-signoff: yes

#1821 [Backport 2.12]: Fix e2e watchdog alert
  go.mod
  go.sum
  tests/pkg/tests/observability_alert_test.go
  tests/pkg/utils/kube_debug.go
  tests/pkg/utils/mco_managedcluster.go
Labels: lgtm, approved, dco-signoff: yes

#1822 Fix Hermetic builds and Enterprise contract violations
  .tekton/endpoint-monitoring-operator-acm-213-pull-request.yaml
  .tekton/endpoint-monitoring-operator-acm-213-push.yaml
  .tekton/grafana-dashboard-loader-acm-213-pull-request.yaml
  .tekton/grafana-dashboard-loader-acm-213-push.yaml
  .tekton/metrics-collector-acm-213-pull-request.yaml
  .tekton/metrics-collector-acm-213-push.yaml
  .tekton/multicluster-observability-operator-acm-213-pull-request.yaml
  .tekton/multicluster-observability-operator-acm-213-push.yaml
  .tekton/rbac-query-proxy-acm-213-pull-request.yaml
  .tekton/rbac-query-proxy-acm-213-push.yaml
  collectors/metrics/Containerfile.operator
  go.mod
  go.sum
  loaders/dashboards/Containerfile.operator
  operators/endpointmetrics/Containerfile.operator
  operators/multiclusterobservability/Containerfile.operator
  proxy/Containerfile.operator
  renovate.json
Labels: lgtm, approved, dco-signoff: yes

#1824 Remove resource limits from observability hub components
  .github/workflows/lint.yaml
  operators/multiclusterobservability/bundle/manifests/multicluster-observability-operator.clusterserviceversion.yaml
  operators/multiclusterobservability/manifests/base/grafana/deployment.yaml
  operators/multiclusterobservability/manifests/base/observatorium/operator.yaml
Labels: lgtm, approved, dco-signoff: yes

#1735 Core automation merge
  Dockerfile.interop
  Jenkinsfile
  cicd-scripts/customize-mco.sh
  cicd-scripts/run-e2e-tests.sh
  examples/configmapcmc/cluster-monitoring-config/cluster-monitoring-config.yaml
  examples/configmapcmc/cluster-monitoring-config/kustomization.yaml
  examples/maxitemsize/updatemcocr/kustomization.yaml
  examples/maxitemsize/updatemcocr/v1beta2-observability-maxitemsize.yaml
  go.mod
  go.sum
  tests/Containerfile.operator
  tests/Dockerfile
  tests/pkg/tests/observability-e2e-test_suite_test.go
  tests/pkg/tests/observability_addon_test.go
  tests/pkg/tests/observability_alert_test.go
  tests/pkg/tests/observability_certrenew_test.go
  tests/pkg/tests/observability_config_test.go
  tests/pkg/tests/observability_dashboard_test.go
  tests/pkg/tests/observability_deployment_test.go
  tests/pkg/tests/observability_endpoint_preserve_test.go
  tests/pkg/tests/observability_export_test.go
  tests/pkg/tests/observability_grafana_dev_test.go
  tests/pkg/tests/observability_grafana_test.go
  tests/pkg/tests/observability_install_test.go
  tests/pkg/tests/observability_manifestwork_test.go
  tests/pkg/tests/observability_metrics_test.go
  tests/pkg/tests/observability_observatorium_preserve_test.go
  tests/pkg/tests/observability_reconcile_test.go
  tests/pkg/tests/observability_retention_test.go
  tests/pkg/tests/observability_route_test.go
  tests/pkg/tests/observability_uninstall_test.go
  tests/pkg/utils/client.go
  tests/pkg/utils/cluster_deploy.go
  tests/pkg/utils/install_config.go
  tests/pkg/utils/kube_debug.go
  tests/pkg/utils/mco_cert_secret.go
  tests/pkg/utils/mco_dashboard.go
  tests/pkg/utils/mco_deploy.go
  tests/pkg/utils/mco_deployments.go
  tests/pkg/utils/mco_grafana.go
  tests/pkg/utils/mco_managedcluster.go
  tests/pkg/utils/mco_pods.go
Labels: lgtm, approved, dco-signoff: no

#1837 Make e2e fail on any errors
  cicd-scripts/run-e2e-tests.sh
Labels: lgtm, approved, dco-signoff: yes

#1836 [release-2.11] Restore non-CVE changes
  collectors/metrics/pkg/metricsclient/metricsclient.go
  collectors/metrics/pkg/metricsclient/metricsclient_test.go
  go.mod
  go.sum
  operators/multiclusterobservability/controllers/multiclusterobservability/predicate_func.go
  operators/multiclusterobservability/controllers/placementrule/placementrule_controller_test.go
  operators/multiclusterobservability/controllers/placementrule/predict_func.go
  operators/multiclusterobservability/pkg/config/config.go
  operators/multiclusterobservability/pkg/config/config_test.go
Labels: lgtm, approved, dco-signoff: yes

#1838 Add managed cluster policy metric to allowlist
  operators/multiclusterobservability/manifests/base/config/metrics_allowlist.yaml
  tests/pkg/tests/observability_metrics_test.go
Labels: lgtm, approved, dco-signoff: yes

#1860 ACM-18001: Make alert ACMRemoteWriteError fire on percentages
  operators/multiclusterobservability/manifests/base/alertmanager/prometheusrule.yaml
Labels: lgtm, approved, dco-signoff: yes

#1877 Konflux for 2.14
  .tekton/endpoint-monitoring-operator-acm-214-pull-request.yaml
  .tekton/endpoint-monitoring-operator-acm-214-push.yaml
  .tekton/grafana-dashboard-loader-acm-214-pull-request.yaml
  .tekton/grafana-dashboard-loader-acm-214-push.yaml
  .tekton/metrics-collector-acm-214-pull-request.yaml
  .tekton/metrics-collector-acm-214-push.yaml
  .tekton/multicluster-observability-operator-acm-214-pull-request.yaml
  .tekton/multicluster-observability-operator-acm-214-push.yaml
  .tekton/rbac-query-proxy-acm-214-pull-request.yaml
  .tekton/rbac-query-proxy-acm-214-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#1878 Verify
  cicd-scripts/run-e2e-tests.sh
  examples/updatemcocr/advancedmcoconfig/kustomization.yaml
  examples/updatemcocr/advancedmcoconfig/v1beta2-observability-custom-mco.yaml
  examples/updatemcocr/initialmcoconfig/kustomization.yaml
  examples/updatemcocr/initialmcoconfig/v1beta2-observability-initial-mco.yaml
  operators/multiclusterobservability/api/v1beta2/zz_generated.deepcopy.go
  tests/pkg/tests/observability_config_test.go
Labels: lgtm, approved, dco-signoff: no

#1879 Konflux: make release-2.13 target release-2.13
  .tekton/endpoint-monitoring-operator-acm-213-pull-request.yaml
  .tekton/endpoint-monitoring-operator-acm-213-push.yaml
  .tekton/grafana-dashboard-loader-acm-213-pull-request.yaml
  .tekton/grafana-dashboard-loader-acm-213-push.yaml
  .tekton/metrics-collector-acm-213-pull-request.yaml
  .tekton/metrics-collector-acm-213-push.yaml
  .tekton/multicluster-observability-operator-acm-213-pull-request.yaml
  .tekton/multicluster-observability-operator-acm-213-push.yaml
  .tekton/rbac-query-proxy-acm-213-pull-request.yaml
  .tekton/rbac-query-proxy-acm-213-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#1882 Verify
  cicd-scripts/run-e2e-tests.sh
  examples/updatemcocr/advancedmcoconfig/kustomization.yaml
  examples/updatemcocr/advancedmcoconfig/v1beta2-observability-custom-mco.yaml
  examples/updatemcocr/initialmcoconfig/kustomization.yaml
  examples/updatemcocr/initialmcoconfig/v1beta2-observability-initial-mco.yaml
  operators/multiclusterobservability/api/v1beta2/zz_generated.deepcopy.go
  tests/pkg/tests/observability_config_test.go
Labels: approved, dco-signoff: no

#1881 Kind: do not copy incompatible binaries to VM & fallback to previous release if no snapshots found
  cicd-scripts/run-e2e-in-kind-via-prow.sh
  scripts/test-utils.sh
Labels: lgtm, approved, dco-signoff: yes
